-- ==========================================
-- ERP Database Initialization Script
-- ==========================================

-- T_PRODUCT: 产品字典表
CREATE TABLE IF NOT EXISTS `T_PRODUCT` (
  `PRODUCT_ID` bigint(20) AUTO_INCREMENT PRIMARY KEY COMMENT '产品自增ID',
  `PN_CODE` varchar(64) NOT NULL COMMENT '产品料号 (PN)',
  `BARCODE` varchar(64) COMMENT '69码/条形码 (EAN-13等)',
  `CATEGORY` varchar(64) COMMENT '产品类别',
  `PRODUCT_GROUP` varchar(64) COMMENT '产品组别',
  `NAME` varchar(255) NOT NULL COMMENT '产品名称',
  `SPECS_JSON` json COMMENT '详细配置/规格参数',
  `STANDARD_PRICE` decimal(10,2) COMMENT '标准售价',
  `CREATE_TIME` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `UPDATE_TIME` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `IS_DELETED` bit(1) DEFAULT b'0' COMMENT '软删除标记',
  UNIQUE KEY `uni_inx_pn_code` (`PN_CODE`),
  KEY `idx_product_barcode` (`BARCODE`),
  KEY `idx_product_category` (`CATEGORY`),
  KEY `idx_product_name` (`NAME`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='标准产品字典表';

-- T_INVENTORY_LOCATION: 库位/仓库类型表
CREATE TABLE IF NOT EXISTS `T_INVENTORY_LOCATION` (
  `LOCATION_ID` varchar(32) PRIMARY KEY COMMENT '库位ID',
  `STORE_ID` varchar(32) NOT NULL COMMENT '归属门店ID',
  `NAME` varchar(64) NOT NULL COMMENT '库位名称',
  `IS_SELLABLE` bit(1) DEFAULT b'1' COMMENT '是否允许直接销售',
  `STATUS` tinyint(4) DEFAULT 1 COMMENT '状态: 1-启用, 0-停用',
  `CREATE_TIME` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `UPDATE_TIME` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  KEY `idx_location_store` (`STORE_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='门店库位结构表';

-- T_INVENTORY_SN: 库存序列号表
CREATE TABLE IF NOT EXISTS `T_INVENTORY_SN` (
  `INVENTORY_ID` varchar(32) PRIMARY KEY COMMENT '库存主键ID',
  `PRODUCT_ID` bigint(20) NOT NULL COMMENT '关联产品字典ID',
  `SN_CODE` varchar(128) NOT NULL COMMENT '商品序列号 (SN)',
  `STORE_ID` varchar(32) COMMENT '当前所属门店ID',
  `LOCATION_ID` varchar(32) COMMENT '当前所在库位ID',
  `STATUS` tinyint(4) DEFAULT 1 COMMENT '库存状态: 1-在库, 2-已销售, 3-调拨中, 4-返修',
  `IMPORT_PRICE` decimal(10,2) COMMENT '实际入库价格',
  `CREATE_TIME` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '系统入库时间',
  `UPDATE_TIME` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  UNIQUE KEY `uni_inx_sn_code` (`SN_CODE`),
  KEY `idx_store_status` (`STORE_ID`, `STATUS`),
  KEY `idx_location_id` (`LOCATION_ID`),
  KEY `idx_product_id` (`PRODUCT_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='库存序列号详情表';

-- T_DISTRIBUTOR: 经销商/代理商表
CREATE TABLE IF NOT EXISTS `T_DISTRIBUTOR` (
  `DISTRIBUTOR_ID` varchar(32) PRIMARY KEY COMMENT '经销商ID',
  `OPEN_ID` varchar(64) COMMENT '微信 OpenID',
  `NAME` varchar(255) NOT NULL COMMENT '经销商名称',
  `ADDRESS` varchar(512) COMMENT '详细地址',
  `PHONE` varchar(32) COMMENT '联系电话',
  `STATUS` tinyint(4) DEFAULT 1 COMMENT '状态: 1-正常, 0-停用',
  `CREATE_TIME` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `UPDATE_TIME` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `IS_DELETED` bit(1) DEFAULT b'0' COMMENT '软删除标记'
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='一级经销商/代理商表';

-- T_STORE: 具体门店/体验店表
CREATE TABLE IF NOT EXISTS `T_STORE` (
  `STORE_ID` varchar(32) PRIMARY KEY COMMENT '门店主键ID',
  `DISTRIBUTOR_ID` varchar(32) COMMENT '所属经销商ID',
  `OPEN_ID` varchar(64) COMMENT '店长微信 OpenID',
  `NAME` varchar(255) NOT NULL COMMENT '门店名称',
  `ADDRESS` varchar(512) COMMENT '门店地址',
  `PHONE` varchar(32) COMMENT '门店固话',
  `MANAGER_STAFF_ID` bigint(20) COMMENT '店长的员工ID',
  `STATUS` tinyint(4) DEFAULT 1 COMMENT '状态: 1-正常, 0-停用',
  `CREATE_TIME` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `UPDATE_TIME` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `IS_DELETED` bit(1) DEFAULT b'0',
  KEY `idx_distributor_id` (`DISTRIBUTOR_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='具体门店/体验店表';

-- T_STAFF: 员工表
CREATE TABLE IF NOT EXISTS `T_STAFF` (
  `STAFF_ID` bigint(20) AUTO_INCREMENT PRIMARY KEY COMMENT '员工自增ID',
  `DISTRIBUTOR_ID` varchar(32) NOT NULL COMMENT '所属经销商ID',
  `STORE_ID` varchar(32) COMMENT '所属门店ID',
  `NAME` varchar(64) NOT NULL COMMENT '员工姓名',
  `PHONE` varchar(32) NOT NULL COMMENT '手机号',
  `PASSWORD_HASH` varchar(128) COMMENT '密码哈希',
  `ROLE` varchar(64) DEFAULT 'staff' COMMENT '角色',
  `STATUS` tinyint(4) DEFAULT 1 COMMENT '状态',
  `CREATE_TIME` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `UPDATE_TIME` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `IS_DELETED` bit(1) DEFAULT b'0' COMMENT '软删除标记',
  UNIQUE KEY `uni_inx_phone` (`PHONE`),
  KEY `idx_distributor_id` (`DISTRIBUTOR_ID`),
  KEY `idx_store_id` (`STORE_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='组织人员结构表';

-- T_ORDER: 销售订单主表
CREATE TABLE IF NOT EXISTS `T_ORDER` (
  `ORDER_ID` varchar(32) PRIMARY KEY COMMENT '系统订单主键',
  `ORDER_NO` varchar(64) NOT NULL COMMENT '业务订单号',
  `STORE_ID` varchar(32) NOT NULL COMMENT '销售门店ID',
  `STORE_NAME` varchar(255) COMMENT '销售门店名称快照',
  `CREATE_USER` varchar(64) COMMENT '制单人姓名',
  `CUSTOMER_ID` varchar(32) COMMENT '关联客户主键ID',
  `CUSTOMER_NAME` varchar(64) COMMENT '客户姓名',
  `CUSTOMER_PHONE` varchar(32) COMMENT '客户电话',
  `CUSTOMER_SOURCE_ID` varchar(64) COMMENT '客户来源 ID',
  `TOTAL_AMOUNT` decimal(10,2) NOT NULL DEFAULT 0.00 COMMENT '订单总金额',
  `DISCOUNT_AMOUNT` decimal(10,2) DEFAULT 0.00 COMMENT '优惠折扣金额',
  `EDUCATION_SUBSIDY` decimal(10,2) DEFAULT 0.00 COMMENT '教育补贴',
  `NATIONAL_SUBSIDY` decimal(10,2) DEFAULT 0.00 COMMENT '国家补贴',
  `ACTUAL_PAYMENT` decimal(10,2) NOT NULL DEFAULT 0.00 COMMENT '实际应付金额',
  `INVOICE_STATUS` varchar(32) DEFAULT '不开票' COMMENT '开票状态',
  `ORDER_STATUS` varchar(32) DEFAULT '已完成' COMMENT '订单状态',
  `CREATE_TIME` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '下单时间',
  `UPDATE_TIME` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `IS_DELETED` bit(1) DEFAULT b'0' COMMENT '软删除标记',
  UNIQUE KEY `uni_inx_order_no` (`ORDER_NO`),
  KEY `idx_store_time` (`STORE_ID`, `CREATE_TIME`),
  KEY `idx_customer_id` (`CUSTOMER_ID`),
  KEY `idx_customer_phone` (`CUSTOMER_PHONE`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='销售订单主表';

-- T_ORDER_ITEM: 订单明细表
CREATE TABLE IF NOT EXISTS `T_ORDER_ITEM` (
  `ITEM_ID` bigint(20) AUTO_INCREMENT PRIMARY KEY COMMENT '明细自增ID',
  `ORDER_ID` varchar(32) NOT NULL COMMENT '关联订单主键',
  `INVENTORY_ID` varchar(32) NOT NULL COMMENT '关联库存SN主键ID',
  `PRODUCT_NAME` varchar(255) COMMENT '商品名称快照',
  `PN_CODE` varchar(64) COMMENT '料号快照',
  `MTM_CODE` varchar(64) COMMENT 'MTM码',
  `SALE_PRICE` decimal(10,2) NOT NULL COMMENT '实际销售单价',
  `QUANTITY` int(11) NOT NULL DEFAULT 1 COMMENT '数量',
  `SUBTOTAL` decimal(10,2) NOT NULL COMMENT '行小计',
  KEY `idx_order_id` (`ORDER_ID`),
  KEY `idx_inventory_id` (`INVENTORY_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='订单商品明细表';

-- T_ORDER_PAYMENT: 订单支付流水表
CREATE TABLE IF NOT EXISTS `T_ORDER_PAYMENT` (
  `PAYMENT_RECORD_ID` bigint(20) AUTO_INCREMENT PRIMARY KEY COMMENT '支付记录自增ID',
  `ORDER_ID` varchar(32) NOT NULL COMMENT '关联订单主键',
  `PAYMENT_METHOD_ID` varchar(64) NOT NULL COMMENT '支付方式标识',
  `AMOUNT` decimal(10,2) NOT NULL COMMENT '支付金额',
  `PAYMENT_TIME` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '支付时间',
  KEY `idx_order_payment` (`ORDER_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='订单支付流水表';

-- T_ORDER_ATTACHMENT: 订单附件凭证表
CREATE TABLE IF NOT EXISTS `T_ORDER_ATTACHMENT` (
  `ATTACH_ID` bigint(20) AUTO_INCREMENT PRIMARY KEY COMMENT '附件自增ID',
  `ORDER_ID` varchar(32) NOT NULL COMMENT '关联订单主键',
  `ATTACH_TYPE` varchar(64) COMMENT '附件类型',
  `FILE_URL` varchar(1024) NOT NULL COMMENT '文件存储路径/URL',
  `UPLOAD_TIME` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '上传时间',
  `SORT_ORDER` int(11) DEFAULT 0 COMMENT '排序',
  KEY `idx_order_attach` (`ORDER_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='订单证明附件表';

-- T_DICT_CUSTOMER_SOURCE: 客户来源字典
CREATE TABLE IF NOT EXISTS `T_DICT_CUSTOMER_SOURCE` (
  `SOURCE_ID` varchar(64) PRIMARY KEY COMMENT '来源ID',
  `NAME` varchar(128) NOT NULL COMMENT '来源名称',
  `STATUS` tinyint(4) DEFAULT 1 COMMENT '状态',
  `SORT_ORDER` int(11) DEFAULT 0 COMMENT '排序号',
  `CREATE_TIME` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `UPDATE_TIME` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  UNIQUE KEY `uni_inx_source_name` (`NAME`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='客户来源配置表';

-- T_DICT_PAYMENT_METHOD: 支付方式字典
CREATE TABLE IF NOT EXISTS `T_DICT_PAYMENT_METHOD` (
  `METHOD_ID` varchar(64) PRIMARY KEY COMMENT '支付方式ID',
  `NAME` varchar(128) NOT NULL COMMENT '支付方式名称',
  `STATUS` tinyint(4) DEFAULT 1 COMMENT '状态',
  `SORT_ORDER` int(11) DEFAULT 0 COMMENT '排序号',
  `CREATE_TIME` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `UPDATE_TIME` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  UNIQUE KEY `uni_inx_method_name` (`NAME`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='支付方式配置表';

-- T_DICT_SUPPLEMENT_ITEM: 附加服务费字典表
CREATE TABLE IF NOT EXISTS `T_DICT_SUPPLEMENT_ITEM` (
  `ITEM_ID` varchar(64) PRIMARY KEY COMMENT '附加项ID',
  `NAME` varchar(128) NOT NULL COMMENT '项目名称',
  `IS_ACTIVE` varchar(10) DEFAULT '1' COMMENT '状态',
  `SORT_ORDER` int(11) DEFAULT 0 COMMENT '排序',
  `CREATE_TIME` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `UPDATE_TIME` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  UNIQUE KEY `uni_inx_sup_name` (`NAME`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='订单附加费用字典表';

-- T_PRINTER_DEVICE: 蓝牙小票打印机设备表
CREATE TABLE IF NOT EXISTS `T_PRINTER_DEVICE` (
  `PRINTER_ID` varchar(64) PRIMARY KEY COMMENT '打印机ID',
  `STORE_ID` varchar(32) NOT NULL COMMENT '归属门店ID',
  `DEVICE_ID` varchar(64) NOT NULL COMMENT '蓝牙MAC',
  `NAME` varchar(128) NOT NULL COMMENT '设备名称',
  `LOCAL_NAME` varchar(128) COMMENT '本地广播名称',
  `CONNECTABLE` bit(1) DEFAULT b'1' COMMENT '是否可连接',
  `RSSI` int(11) COMMENT '信号强度',
  `ADVERTISE_SERVICE_UUIDS` text COMMENT '蓝牙服务UUID列表',
  `CREATE_TIME` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `UPDATE_TIME` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  UNIQUE KEY `uni_inx_device` (`DEVICE_ID`),
  KEY `idx_printer_store` (`STORE_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='门店蓝牙打印机设备表';

-- T_CUSTOMER: 客户/会员主表
CREATE TABLE IF NOT EXISTS `T_CUSTOMER` (
  `CUSTOMER_ID` varchar(32) PRIMARY KEY COMMENT '客户单主键ID',
  `DISTRIBUTOR_ID` varchar(32) NOT NULL COMMENT '归属经销商ID',
  `NAME` varchar(64) NOT NULL COMMENT '客户姓名',
  `PHONE` varchar(32) NOT NULL COMMENT '客户手机号',
  `CUSTOMER_TYPE` varchar(32) DEFAULT 'retail' COMMENT '客户类型',
  `TOTAL_SPEND` decimal(10,2) DEFAULT 0.00 COMMENT '累计消费总额',
  `ORDER_COUNT` int(11) DEFAULT 0 COMMENT '累计下单次数',
  `REGISTER_STORE_ID` varchar(32) COMMENT '首次登记门店ID',
  `CREATE_TIME` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `UPDATE_TIME` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  UNIQUE KEY `uni_inx_customer_phone` (`PHONE`),
  KEY `idx_customer_distributor` (`DISTRIBUTOR_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='客户/会员主表';

-- T_INBOUND_ORDER: 入库单主表
CREATE TABLE IF NOT EXISTS `T_INBOUND_ORDER` (
  `INBOUND_ID` varchar(32) PRIMARY KEY COMMENT '入库单主键',
  `INBOUND_NO` varchar(64) NOT NULL COMMENT '业务入库单号',
  `STORE_ID` varchar(32) NOT NULL COMMENT '收货门店ID',
  `SUPPLIER_NAME` varchar(128) COMMENT '供应商名称',
  `TOTAL_QUANTITY` int(11) DEFAULT 0 COMMENT '总计入库数量',
  `TOTAL_AMOUNT` decimal(10,2) DEFAULT 0.00 COMMENT '总计采购金额',
  `STATUS` varchar(32) DEFAULT 'pending' COMMENT '状态',
  `CREATE_USER` varchar(64) COMMENT '制单人姓名',
  `CREATE_TIME` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `UPDATE_TIME` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  UNIQUE KEY `uni_inx_inbound_no` (`INBOUND_NO`),
  KEY `idx_inbound_store` (`STORE_ID`, `CREATE_TIME`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='采购/调拨入库单主表';

-- T_INBOUND_ITEM: 入库明细单
CREATE TABLE IF NOT EXISTS `T_INBOUND_ITEM` (
  `ITEM_ID` bigint(20) AUTO_INCREMENT PRIMARY KEY,
  `INBOUND_ID` varchar(32) NOT NULL COMMENT '关联入库单主键',
  `PRODUCT_ID` bigint(20) NOT NULL COMMENT '关联产品ID',
  `SN_CODE` varchar(128) COMMENT '序列号',
  `IMPORT_PRICE` decimal(10,2) COMMENT '采购进价',
  `QUANTITY` int(11) DEFAULT 1 COMMENT '数量',
  KEY `idx_inbound_id` (`INBOUND_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='入库单明细表';

-- T_INVENTORY_TRANSFER: 库存调拨单表
CREATE TABLE IF NOT EXISTS `T_INVENTORY_TRANSFER` (
  `TRANSFER_ID` varchar(32) PRIMARY KEY COMMENT '调拨单主键',
  `TRANSFER_NO` varchar(64) NOT NULL COMMENT '业务调拨单号',
  `FROM_STORE_ID` varchar(32) NOT NULL COMMENT '调出方门店ID',
  `TO_STORE_ID` varchar(32) NOT NULL COMMENT '调入方门店ID',
  `TOTAL_QUANTITY` int(11) DEFAULT 0 COMMENT '调拨总数',
  `STATUS` varchar(32) DEFAULT 'shipping' COMMENT '状态',
  `APPLY_USER` varchar(64) COMMENT '申请人',
  `CONFIRM_USER` varchar(64) COMMENT '接收确认人',
  `CREATE_TIME` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `UPDATE_TIME` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  UNIQUE KEY `uni_inx_transfer_no` (`TRANSFER_NO`),
  KEY `idx_transfer_from_to` (`FROM_STORE_ID`, `TO_STORE_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='门店库存调拨主表';

-- T_TRANSFER_ITEM: 调拨明细表
CREATE TABLE IF NOT EXISTS `T_TRANSFER_ITEM` (
  `ITEM_ID` bigint(20) AUTO_INCREMENT PRIMARY KEY,
  `TRANSFER_ID` varchar(32) NOT NULL COMMENT '关联调拨单',
  `INVENTORY_ID` varchar(32) NOT NULL COMMENT '关联库存SN主键ID',
  KEY `idx_transfer_id` (`TRANSFER_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='调拨机器明细表';

-- T_RETURN_ORDER: 售后退换单
CREATE TABLE IF NOT EXISTS `T_RETURN_ORDER` (
  `RETURN_ID` varchar(32) PRIMARY KEY COMMENT '售后退换主键',
  `RETURN_NO` varchar(64) NOT NULL COMMENT '业务退换号',
  `ORIGINAL_ORDER_ID` varchar(32) NOT NULL COMMENT '原销售订单ID',
  `STORE_ID` varchar(32) NOT NULL COMMENT '处理门店ID',
  `RETURN_TYPE` varchar(32) NOT NULL COMMENT '类型',
  `REFUND_AMOUNT` decimal(10,2) DEFAULT 0.00 COMMENT '退回金额',
  `REASON` varchar(255) COMMENT '原因',
  `STATUS` varchar(32) DEFAULT 'processing' COMMENT '状态',
  `CREATE_TIME` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `UPDATE_TIME` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  UNIQUE KEY `uni_inx_return_no` (`RETURN_NO`),
  KEY `idx_return_store` (`STORE_ID`, `CREATE_TIME`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='售后退换单主表';

-- T_DAILY_STATEMENT: 门店日结对账单
CREATE TABLE IF NOT EXISTS `T_DAILY_STATEMENT` (
  `STATEMENT_ID` varchar(32) PRIMARY KEY COMMENT '日结单主键',
  `STORE_ID` varchar(32) NOT NULL COMMENT '门店ID',
  `STATEMENT_DATE` date NOT NULL COMMENT '日结账单日期',
  `TOTAL_REVENUE` decimal(10,2) DEFAULT 0.00 COMMENT '当日总营业额',
  `TOTAL_REFUND` decimal(10,2) DEFAULT 0.00 COMMENT '当日总退款退单额',
  `CASH_AMOUNT` decimal(10,2) DEFAULT 0.00 COMMENT '现金收入',
  `WECHAT_ALIPAY_AMOUNT` decimal(10,2) DEFAULT 0.00 COMMENT '微信支付宝收入',
  `DIFFERENCE_AMOUNT` decimal(10,2) DEFAULT 0.00 COMMENT '账实差异',
  `SUBMIT_STAFF_ID` bigint(20) COMMENT '盘点员工',
  `STATUS` varchar(32) DEFAULT 'draft' COMMENT '状态',
  `CREATE_TIME` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `UPDATE_TIME` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  UNIQUE KEY `uni_idx_store_date` (`STORE_ID`, `STATEMENT_DATE`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='门店日结对账单主表';
