-- 实际生产 MySQL 结构的订单归档修复。
-- 规则：应用层使用 pnCode / snCode；MySQL 只使用 PN_CODE / SN_CODE。
-- 执行前请确认已备份 T_ORDER_ITEM。
START TRANSACTION;

-- 统一 PN、SN 的值格式，并用商品 PN 主表补齐已有商品的订单快照。
UPDATE T_PRODUCT_PN
SET PN_CODE = UPPER(TRIM(PN_CODE))
WHERE PN_CODE IS NOT NULL AND TRIM(PN_CODE) <> '';

UPDATE T_PRODUCT_SN sn
LEFT JOIN T_PRODUCT_PN pn ON pn.PN_ID = sn.PN_ID
SET sn.SN_CODE = UPPER(TRIM(sn.SN_CODE)),
    sn.pn_code = UPPER(TRIM(COALESCE(NULLIF(sn.pn_code, ''), pn.PN_CODE)))
WHERE sn.SN_CODE IS NOT NULL AND TRIM(sn.SN_CODE) <> '';

UPDATE T_ORDER_ITEM oi
SET oi.PRODUCT_ID = NULLIF(TRIM(oi.PRODUCT_ID), ''),
    oi.PRODUCT_NAME = NULLIF(TRIM(oi.PRODUCT_NAME), ''),
    oi.PN_CODE = UPPER(NULLIF(TRIM(oi.PN_CODE), '')),
    oi.SN_ID = NULLIF(TRIM(oi.SN_ID), ''),
    oi.SN_CODE = UPPER(NULLIF(TRIM(oi.SN_CODE), ''))
WHERE oi.ITEM_ID IS NOT NULL;

UPDATE T_ORDER_ITEM oi
SET oi.PN_CODE = (
  SELECT UPPER(TRIM(pp.PN_CODE))
  FROM T_PRODUCT_PN pp
  WHERE pp.PRODUCT_ID = oi.PRODUCT_ID
    AND pp.IS_DELETED = 0
    AND COALESCE(pp.STATUS, 1) = 1
  ORDER BY pp.IS_PRIMARY DESC, pp.UPDATE_TIME DESC, pp.PN_ID
  LIMIT 1
)
WHERE oi.PRODUCT_ID IS NOT NULL
  AND (oi.PN_CODE IS NULL OR oi.PN_CODE = '');

-- 删除明确的空白零金额明细；有商品名、金额、PN 或 SN 的历史明细保留，避免误删业务记录。
DELETE FROM T_ORDER_ITEM
WHERE (PRODUCT_ID IS NULL OR TRIM(PRODUCT_ID) = '')
  AND (PRODUCT_NAME IS NULL OR TRIM(PRODUCT_NAME) = '')
  AND (PN_CODE IS NULL OR TRIM(PN_CODE) = '')
  AND (SN_CODE IS NULL OR TRIM(SN_CODE) = '')
  AND COALESCE(SALE_PRICE, 0) = 0
  AND COALESCE(SUBTOTAL, 0) = 0;

COMMIT;
