-- 费用经营归属与员工绩效毛利分摊。
-- 服务启动时由 ensureExpenseAccountingSchema 以幂等方式执行结构检查和历史月份回填。
ALTER TABLE T_EXPENSE
  ADD COLUMN ACCOUNTING_MONTH VARCHAR(7) NULL COMMENT '费用经营归属月份，格式 YYYY-MM' AFTER EXPENSE_DATE,
  ADD COLUMN AFFECTS_STORE_PROFIT TINYINT(1) NOT NULL DEFAULT 1 COMMENT '是否计入门店经营费用' AFTER ACCOUNTING_MONTH;

CREATE TABLE IF NOT EXISTS T_EXPENSE_PERFORMANCE_ALLOCATION (
  ALLOCATION_ID VARCHAR(32) NOT NULL,
  ALLOCATION_NO VARCHAR(64) NOT NULL,
  EXPENSE_ID VARCHAR(32) NOT NULL,
  EXPENSE_NO VARCHAR(64) NOT NULL,
  DISTRIBUTOR_ID VARCHAR(32),
  REGION_ID VARCHAR(32),
  STORE_ID VARCHAR(32) NOT NULL,
  PERFORMANCE_MONTH VARCHAR(7) NOT NULL,
  STAFF_ID BIGINT NOT NULL,
  STAFF_NAME VARCHAR(64) NOT NULL,
  AMOUNT DECIMAL(12,2) NOT NULL,
  REASON VARCHAR(1000) NOT NULL,
  STATUS VARCHAR(32) NOT NULL DEFAULT 'pending_finance',
  APPLICANT_STAFF_ID BIGINT NOT NULL,
  APPLICANT_NAME VARCHAR(64) NOT NULL,
  FINANCE_REVIEWER_ID BIGINT,
  FINANCE_REVIEWER_NAME VARCHAR(64),
  FINANCE_REVIEW_COMMENT VARCHAR(512),
  FINANCE_REVIEW_TIME DATETIME,
  ADMIN_REVIEWER_ID BIGINT,
  ADMIN_REVIEWER_NAME VARCHAR(64),
  ADMIN_REVIEW_COMMENT VARCHAR(512),
  ADMIN_REVIEW_TIME DATETIME,
  REJECT_STAGE VARCHAR(32),
  CREATE_TIME DATETIME DEFAULT CURRENT_TIMESTAMP,
  UPDATE_TIME DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (ALLOCATION_ID),
  UNIQUE KEY UK_EXPENSE_PERFORMANCE_ALLOCATION_NO (ALLOCATION_NO),
  KEY IDX_EXPENSE_PERFORMANCE_EXPENSE (EXPENSE_ID, STATUS),
  KEY IDX_EXPENSE_PERFORMANCE_MONTH (STORE_ID, PERFORMANCE_MONTH, STATUS),
  KEY IDX_EXPENSE_PERFORMANCE_STAFF (STAFF_ID, PERFORMANCE_MONTH, STATUS)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='费用对员工绩效毛利分摊';

CREATE TABLE IF NOT EXISTS T_EXPENSE_ACCOUNTING_PERIOD (
  PERIOD_ID VARCHAR(32) NOT NULL,
  DISTRIBUTOR_ID VARCHAR(32) NOT NULL,
  MONTH_KEY VARCHAR(7) NOT NULL,
  STATUS VARCHAR(16) NOT NULL DEFAULT 'open',
  CLOSED_STAFF_ID BIGINT,
  CLOSED_USER VARCHAR(64),
  CLOSED_TIME DATETIME,
  REOPENED_STAFF_ID BIGINT,
  REOPENED_USER VARCHAR(64),
  REOPENED_TIME DATETIME,
  REMARK VARCHAR(512),
  CREATE_TIME DATETIME DEFAULT CURRENT_TIMESTAMP,
  UPDATE_TIME DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (PERIOD_ID),
  UNIQUE KEY UK_EXPENSE_ACCOUNTING_PERIOD (DISTRIBUTOR_ID, MONTH_KEY),
  KEY IDX_EXPENSE_ACCOUNTING_PERIOD_STATUS (DISTRIBUTOR_ID, STATUS, MONTH_KEY)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='费用经营月份锁定';
