-- 月度任务配置及实时达成所需数据表。
CREATE TABLE IF NOT EXISTS T_MONTHLY_TASK (
  TASK_ID VARCHAR(32) NOT NULL,
  DISTRIBUTOR_ID VARCHAR(32) NOT NULL,
  MONTH_KEY VARCHAR(7) NOT NULL,
  TARGET_TYPE VARCHAR(16) NOT NULL,
  TARGET_ID VARCHAR(32) NOT NULL,
  SALES_TARGET DECIMAL(12,2) NOT NULL DEFAULT 0,
  GROSS_PROFIT_TARGET DECIMAL(12,2) NOT NULL DEFAULT 0,
  STATUS TINYINT(1) NOT NULL DEFAULT 1,
  CREATE_STAFF_ID BIGINT,
  CREATE_USER VARCHAR(64),
  UPDATE_STAFF_ID BIGINT,
  UPDATE_USER VARCHAR(64),
  CREATE_TIME DATETIME DEFAULT CURRENT_TIMESTAMP,
  UPDATE_TIME DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (TASK_ID),
  UNIQUE KEY uk_monthly_task_scope (DISTRIBUTOR_ID, MONTH_KEY, TARGET_TYPE, TARGET_ID),
  KEY idx_monthly_task_month (DISTRIBUTOR_ID, MONTH_KEY, TARGET_TYPE, STATUS)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='月度任务目标';

CREATE TABLE IF NOT EXISTS T_MONTHLY_TASK_PRODUCT_BATCH (
  BATCH_ID VARCHAR(32) NOT NULL,
  TASK_ID VARCHAR(32) NOT NULL,
  BATCH_NAME VARCHAR(128) NOT NULL,
  SORT_ORDER INT NOT NULL DEFAULT 0,
  CREATE_TIME DATETIME DEFAULT CURRENT_TIMESTAMP,
  UPDATE_TIME DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (BATCH_ID),
  KEY idx_monthly_task_batch_task (TASK_ID, SORT_ORDER)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='月度任务商品批次';

CREATE TABLE IF NOT EXISTS T_MONTHLY_TASK_PRODUCT (
  ID BIGINT NOT NULL AUTO_INCREMENT,
  BATCH_ID VARCHAR(32) NOT NULL,
  PRODUCT_ID VARCHAR(32) NOT NULL,
  PRODUCT_NAME VARCHAR(255) NOT NULL,
  TARGET_QUANTITY INT NOT NULL DEFAULT 0,
  CREATE_TIME DATETIME DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (ID),
  UNIQUE KEY uk_monthly_task_batch_product (BATCH_ID, PRODUCT_ID),
  KEY idx_monthly_task_product_product (PRODUCT_ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='月度任务批次商品目标';

CREATE TABLE IF NOT EXISTS T_MONTHLY_TASK_GROSS_PROFIT_ALLOCATION (
  ALLOCATION_ID VARCHAR(32) NOT NULL,
  TASK_ID VARCHAR(32) NOT NULL,
  STAFF_ID BIGINT NOT NULL,
  ALLOCATED_TARGET DECIMAL(12,2) NOT NULL DEFAULT 0,
  CREATE_STAFF_ID BIGINT,
  CREATE_USER VARCHAR(64),
  UPDATE_STAFF_ID BIGINT,
  UPDATE_USER VARCHAR(64),
  CREATE_TIME DATETIME DEFAULT CURRENT_TIMESTAMP,
  UPDATE_TIME DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (ALLOCATION_ID),
  UNIQUE KEY uk_monthly_task_gp_staff (TASK_ID, STAFF_ID),
  KEY idx_monthly_task_gp_staff (STAFF_ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='门店月度任务毛利员工分摊';
