-- ==========================================
-- ANY-ERP 数据库初始化脚本 v1.0
-- ==========================================

SET NAMES utf8mb4;
SET FOREIGN_KEY_CHECKS = 0;

-- -------------------------------------------
-- 一、组织架构
-- -------------------------------------------

-- T_REGION: 区域表
DROP TABLE IF EXISTS T_REGION;
CREATE TABLE T_REGION (
  REGION_ID     VARCHAR(32) PRIMARY KEY COMMENT '区域ID',
  REGION_CODE   VARCHAR(32) NOT NULL UNIQUE COMMENT '区域代码(CD/CQ/DS)',
  NAME          VARCHAR(128) NOT NULL COMMENT '区域名称',
  SORT_ORDER    INT DEFAULT 0 COMMENT '排序',
  STATUS        TINYINT DEFAULT 1 COMMENT '状态：1-启用，0-停用',
  CREATE_TIME   TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  UPDATE_TIME   TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='区域表';

-- T_DISTRIBUTOR: 经销商/股东表
DROP TABLE IF EXISTS T_DISTRIBUTOR;
CREATE TABLE T_DISTRIBUTOR (
  DISTRIBUTOR_ID VARCHAR(32) PRIMARY KEY COMMENT '经销商ID',
  REGION_ID      VARCHAR(32) COMMENT '所属区域',
  NAME           VARCHAR(255) NOT NULL COMMENT '名称',
  EQUITY_RATIO  DECIMAL(5,2) COMMENT '股权比例(%)',
  PHONE         VARCHAR(32) COMMENT '联系电话',
  ADDRESS       VARCHAR(512) COMMENT '地址',
  STATUS        TINYINT DEFAULT 1 COMMENT '状态：1-正常，0-停用',
  CREATE_TIME   TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  UPDATE_TIME   TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  IS_DELETED    TINYINT(1) DEFAULT 0,
  KEY idx_region (REGION_ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='经销商/股东表';

-- T_STORE: 门店表
DROP TABLE IF EXISTS T_STORE;
CREATE TABLE T_STORE (
  STORE_ID      VARCHAR(32) PRIMARY KEY COMMENT '门店ID',
  DISTRIBUTOR_ID VARCHAR(32) COMMENT '所属经销商',
  REGION_ID     VARCHAR(32) COMMENT '所属区域',
  NAME          VARCHAR(255) NOT NULL COMMENT '门店名称',
  ADDRESS       VARCHAR(512) COMMENT '门店地址',
  PHONE         VARCHAR(32) COMMENT '门店电话',
  STATUS        TINYINT DEFAULT 1 COMMENT '状态：1-正常，0-停用',
  CREATE_TIME   TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  UPDATE_TIME   TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  IS_DELETED    TINYINT(1) DEFAULT 0,
  KEY idx_distributor (DISTRIBUTOR_ID),
  KEY idx_region (REGION_ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='门店表';

-- T_STAFF: 员工表
DROP TABLE IF EXISTS T_STAFF;
CREATE TABLE T_STAFF (
  STAFF_ID      BIGINT(20) AUTO_INCREMENT PRIMARY KEY COMMENT '员工ID',
  DISTRIBUTOR_ID VARCHAR(32) NOT NULL COMMENT '所属经销商',
  STORE_ID      VARCHAR(32) COMMENT '所属门店',
  REGION_ID     VARCHAR(32) COMMENT '所属区域',
  NAME          VARCHAR(64) NOT NULL COMMENT '员工姓名',
  PHONE         VARCHAR(32) NOT NULL COMMENT '手机号(登录账号)',
  PASSWORD_HASH VARCHAR(128) COMMENT '密码哈希',
  ROLE_CODE     VARCHAR(32) DEFAULT 'staff' COMMENT '角色代码',
  STATUS        TINYINT DEFAULT 1 COMMENT '状态：1-正常，0-停用',
  CREATE_TIME   TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  UPDATE_TIME   TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  IS_DELETED    TINYINT(1) DEFAULT 0,
  UNIQUE KEY uni_phone (PHONE),
  KEY idx_distributor (DISTRIBUTOR_ID),
  KEY idx_store (STORE_ID),
  KEY idx_region (REGION_ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='员工表';

-- -------------------------------------------
-- 二、权限管理
-- -------------------------------------------

-- T_MENU: 菜单表
DROP TABLE IF EXISTS T_MENU;
CREATE TABLE T_MENU (
  MENU_ID       VARCHAR(32) PRIMARY KEY COMMENT '菜单ID',
  MENU_CODE    VARCHAR(64) NOT NULL UNIQUE COMMENT '菜单代码',
  NAME         VARCHAR(128) NOT NULL COMMENT '菜单名称',
  PARENT_ID    VARCHAR(32) COMMENT '父级菜单ID',
  MENU_TYPE    VARCHAR(16) COMMENT '类型：module-模块，menu-菜单，button-按钮',
  PATH         VARCHAR(256) COMMENT '路由路径',
  ICON         VARCHAR(64) COMMENT '图标',
  SORT_ORDER   INT DEFAULT 0,
  STATUS       TINYINT DEFAULT 1,
  CREATE_TIME  TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  UPDATE_TIME  TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='菜单表';

-- T_ROLE: 角色表
DROP TABLE IF EXISTS T_ROLE;
CREATE TABLE T_ROLE (
  ROLE_ID       VARCHAR(32) PRIMARY KEY COMMENT '角色ID',
  ROLE_CODE    VARCHAR(64) NOT NULL UNIQUE COMMENT '角色代码',
  NAME         VARCHAR(128) NOT NULL COMMENT '角色名称',
  DESCRIPTION  VARCHAR(512) COMMENT '描述',
  IS_SYSTEM    TINYINT(1) DEFAULT 0 COMMENT '是否系统角色',
  STATUS       TINYINT DEFAULT 1,
  CREATE_TIME  TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  UPDATE_TIME  TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='角色表';

-- T_ROLE_MENU: 角色菜单关联表
DROP TABLE IF EXISTS T_ROLE_MENU;
CREATE TABLE T_ROLE_MENU (
  ID          BIGINT(20) AUTO_INCREMENT PRIMARY KEY,
  ROLE_ID     VARCHAR(32) NOT NULL,
  MENU_ID     VARCHAR(32) NOT NULL,
  CREATE_TIME TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  UNIQUE KEY uni_role_menu (ROLE_ID, MENU_ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='角色菜单关联表';

-- T_STAFF_ROLE: 员工角色关联表
DROP TABLE IF EXISTS T_STAFF_ROLE;
CREATE TABLE T_STAFF_ROLE (
  ID          BIGINT(20) AUTO_INCREMENT PRIMARY KEY,
  STAFF_ID    VARCHAR(32) NOT NULL,
  ROLE_ID     VARCHAR(32) NOT NULL,
  CREATE_TIME TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  UNIQUE KEY uni_staff_role (STAFF_ID, ROLE_ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='员工角色关联表';

-- T_REGION_PERMISSION: 区域数据权限表
DROP TABLE IF EXISTS T_REGION_PERMISSION;
CREATE TABLE T_REGION_PERMISSION (
  ID           BIGINT(20) AUTO_INCREMENT PRIMARY KEY,
  STAFF_ID     VARCHAR(32) NOT NULL COMMENT '员工ID',
  REGION_CODE  VARCHAR(32) NOT NULL COMMENT '区域代码',
  CAN_VIEW     TINYINT(1) DEFAULT 1 COMMENT '可查看',
  CAN_MANAGE   TINYINT(1) DEFAULT 0 COMMENT '可管理',
  CREATE_TIME  TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  KEY idx_staff (STAFF_ID),
  KEY idx_region (REGION_CODE)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='区域数据权限表';

-- -------------------------------------------
-- 三、商品模块
-- -------------------------------------------

-- T_PRODUCT: 商品主表
DROP TABLE IF EXISTS T_PRODUCT;
CREATE TABLE T_PRODUCT (
  PRODUCT_ID      VARCHAR(32) PRIMARY KEY COMMENT '商品ID',
  PRODUCT_CODE    VARCHAR(32) NOT NULL UNIQUE COMMENT '商品编号(P+日期+序号)',
  NAME            VARCHAR(255) NOT NULL COMMENT '商品名称',
  CATEGORY        VARCHAR(64) COMMENT '产品类别',
  NEED_SN         TINYINT(1) DEFAULT 0 COMMENT '是否需要SN',
  NEED_IMEI       TINYINT(1) DEFAULT 0 COMMENT '是否需要IMEI',
  STANDARD_PRICE  DECIMAL(12,2) COMMENT '标准售价',
  COST_PRICE      DECIMAL(12,2) COMMENT '标准成本',
  UNIT            VARCHAR(16) DEFAULT '台' COMMENT '单位',
  SPECS_JSON      JSON COMMENT '规格参数(颜色/容量/版本等)',
  REMARK          VARCHAR(512) COMMENT '备注',
  STATUS          TINYINT DEFAULT 1 COMMENT '状态：1-启用，0-停用',
  CREATE_TIME     TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  UPDATE_TIME     TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  IS_DELETED      TINYINT(1) DEFAULT 0,
  KEY idx_product_code (PRODUCT_CODE),
  KEY idx_category (CATEGORY),
  KEY idx_name (NAME)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='商品主表';

-- T_PRODUCT_PN: 商品PN料号表
DROP TABLE IF EXISTS T_PRODUCT_PN;
CREATE TABLE T_PRODUCT_PN (
  PN_ID        VARCHAR(32) PRIMARY KEY COMMENT 'PN ID',
  PRODUCT_ID   VARCHAR(32) NOT NULL COMMENT '关联商品ID',
  PN_CODE      VARCHAR(64) NOT NULL COMMENT 'PN料号',
  BARCODE      VARCHAR(64) COMMENT '条形码(69码)',
  IS_PRIMARY   TINYINT(1) DEFAULT 0 COMMENT '是否主料号',
  STATUS       TINYINT DEFAULT 1,
  CREATE_TIME  TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  UPDATE_TIME  TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  IS_DELETED   TINYINT(1) DEFAULT 0,
  UNIQUE KEY uni_pn_code (PN_CODE),
  KEY idx_product_pn (PRODUCT_ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='商品PN料号表';

-- T_PRODUCT_SN: 商品序列号表
DROP TABLE IF EXISTS T_PRODUCT_SN;
CREATE TABLE T_PRODUCT_SN (
  SN_ID         VARCHAR(32) PRIMARY KEY COMMENT 'SN ID',
  PRODUCT_ID    VARCHAR(32) NOT NULL COMMENT '关联商品ID',
  PN_ID         VARCHAR(32) COMMENT '关联PN ID',
  SN_CODE       VARCHAR(128) NOT NULL COMMENT '序列号',
  IMEI1         VARCHAR(32) COMMENT 'IMEI1(手机类)',
  IMEI2         VARCHAR(32) COMMENT 'IMEI2(手机类)',
  STATUS        VARCHAR(32) DEFAULT 'in_stock' COMMENT '状态:in_stock-在库,sold-已销售,transferring-调拨中,repair-返修',
  STORE_ID      VARCHAR(32) COMMENT '当前门店',
  LOCATION_ID   VARCHAR(32) COMMENT '当前库位',
  INBOUND_TIME  TIMESTAMP COMMENT '入库时间',
  INBOUND_PRICE DECIMAL(12,2) COMMENT '入库价格',
  BATCH_NO      VARCHAR(64) COMMENT '批次号(FIFO)',
  REMARK        VARCHAR(255) COMMENT '备注',
  CREATE_TIME   TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  UPDATE_TIME   TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  IS_DELETED    TINYINT(1) DEFAULT 0,
  UNIQUE KEY uni_sn_code (SN_CODE),
  KEY idx_product_sn (PRODUCT_ID),
  KEY idx_store_status (STORE_ID, STATUS),
  KEY idx_batch (BATCH_NO)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='商品序列号表';

-- -------------------------------------------
-- 四、库房管理
-- -------------------------------------------

-- T_LOCATION: 库位表
DROP TABLE IF EXISTS T_LOCATION;
CREATE TABLE T_LOCATION (
  LOCATION_ID  VARCHAR(32) PRIMARY KEY COMMENT '库位ID',
  STORE_ID     VARCHAR(32) NOT NULL COMMENT '所属门店',
  NAME         VARCHAR(64) NOT NULL COMMENT '库位名称',
  TYPE         VARCHAR(32) DEFAULT 'normal' COMMENT '类型:normal-普通,defective-残次区',
  IS_SELLABLE  TINYINT(1) DEFAULT 1 COMMENT '是否允许销售',
  STATUS       TINYINT DEFAULT 1,
  CREATE_TIME  TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  UPDATE_TIME  TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  KEY idx_location_store (STORE_ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='库位表';

-- T_INVENTORY_WARNING: 库存预警配置表
DROP TABLE IF EXISTS T_INVENTORY_WARNING;
CREATE TABLE T_INVENTORY_WARNING (
  WARNING_ID   VARCHAR(32) PRIMARY KEY,
  PRODUCT_ID   VARCHAR(32) COMMENT '商品ID(为空按类别)',
  CATEGORY     VARCHAR(64) COMMENT '商品类别',
  MIN_STOCK    INT DEFAULT 0 COMMENT '最低库存预警',
  AGING_DAYS   INT DEFAULT 90 COMMENT '库龄预警天数',
  WARNING_TYPE VARCHAR(32) COMMENT '类型:low_stock-库存不足,aging-库龄超期',
  STATUS       TINYINT DEFAULT 1,
  CREATE_TIME  TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  UPDATE_TIME  TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  KEY idx_product_warning (PRODUCT_ID),
  KEY idx_category_warning (CATEGORY)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='库存预警配置表';

-- -------------------------------------------
-- 五、采购管理
-- -------------------------------------------

-- T_SUPPLIER: 供应商表
DROP TABLE IF EXISTS T_SUPPLIER;
CREATE TABLE T_SUPPLIER (
  SUPPLIER_ID   VARCHAR(32) PRIMARY KEY,
  NAME          VARCHAR(255) NOT NULL COMMENT '供应商名称',
  CONTACT       VARCHAR(64) COMMENT '联系人',
  PHONE         VARCHAR(32) COMMENT '联系电话',
  ADDRESS       VARCHAR(512) COMMENT '地址',
  STATUS        TINYINT DEFAULT 1,
  CREATE_TIME   TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  UPDATE_TIME   TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  IS_DELETED    TINYINT(1) DEFAULT 0
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='供应商表';

-- T_PURCHASE_REQUEST: 采购申请表
DROP TABLE IF EXISTS T_PURCHASE_REQUEST;
CREATE TABLE T_PURCHASE_REQUEST (
  REQUEST_ID    VARCHAR(32) PRIMARY KEY COMMENT '申请单ID',
  REQUEST_NO   VARCHAR(64) NOT NULL UNIQUE COMMENT '申请单号',
  STORE_ID     VARCHAR(32) NOT NULL COMMENT '申请门店',
  SUPPLIER_ID  VARCHAR(32) COMMENT '供应商',
  TOTAL_AMOUNT DECIMAL(12,2) COMMENT '申请金额',
  REASON       TEXT COMMENT '申请原因',
  STATUS       VARCHAR(32) DEFAULT 'pending' COMMENT '状态:pending-待审批,approved-已审批,rejected-已拒绝,purchased-已采购',
  APPLY_USER   VARCHAR(64) COMMENT '申请人',
  APPROVE_USER VARCHAR(64) COMMENT '审批人',
  APPROVE_COMMENT VARCHAR(512) COMMENT '审批意见',
  CREATE_TIME  TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  UPDATE_TIME  TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  KEY idx_request_store (STORE_ID),
  KEY idx_request_status (STATUS)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='采购申请表';

-- T_PURCHASE_REQUEST_ITEM: 采购申请明细
DROP TABLE IF EXISTS T_PURCHASE_REQUEST_ITEM;
CREATE TABLE T_PURCHASE_REQUEST_ITEM (
  ITEM_ID      BIGINT(20) AUTO_INCREMENT PRIMARY KEY,
  REQUEST_ID   VARCHAR(32) NOT NULL COMMENT '关联申请单',
  PRODUCT_ID   VARCHAR(32) NOT NULL COMMENT '商品ID',
  PRODUCT_NAME VARCHAR(255) COMMENT '商品名称(快照)',
  PN_CODE     VARCHAR(64) COMMENT 'PN料号(快照)',
  QUANTITY    INT NOT NULL COMMENT '申请数量',
  UNIT_PRICE  DECIMAL(12,2) COMMENT '期望单价',
  SUBTOTAL    DECIMAL(12,2) COMMENT '小计',
  KEY idx_request_item (REQUEST_ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='采购申请明细表';

-- T_PURCHASE_ORDER: 采购单主表
DROP TABLE IF EXISTS T_PURCHASE_ORDER;
CREATE TABLE T_PURCHASE_ORDER (
  ORDER_ID     VARCHAR(32) PRIMARY KEY COMMENT '采购单ID',
  ORDER_NO    VARCHAR(64) NOT NULL UNIQUE COMMENT '采购单号',
  REQUEST_ID  VARCHAR(32) COMMENT '关联申请单',
  STORE_ID   VARCHAR(32) NOT NULL COMMENT '收货门店',
  SUPPLIER_ID VARCHAR(32) NOT NULL COMMENT '供应商',
  TOTAL_AMOUNT DECIMAL(12,2) COMMENT '采购总金额',
  TOTAL_QUANTITY INT COMMENT '采购总数量',
  STATUS     VARCHAR(32) DEFAULT 'purchased' COMMENT '状态:purchased-已采购,partial_inbound-部分入库,completed-已完成',
  CREATE_USER VARCHAR(64) COMMENT '制单人',
  CREATE_TIME TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  UPDATE_TIME TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  KEY idx_purchase_store (STORE_ID),
  KEY idx_purchase_supplier (SUPPLIER_ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='采购单主表';

-- T_PURCHASE_ORDER_ITEM: 采购单明细
DROP TABLE IF EXISTS T_PURCHASE_ORDER_ITEM;
CREATE TABLE T_PURCHASE_ORDER_ITEM (
  ITEM_ID      BIGINT(20) AUTO_INCREMENT PRIMARY KEY,
  ORDER_ID     VARCHAR(32) NOT NULL,
  PRODUCT_ID   VARCHAR(32) NOT NULL,
  PRODUCT_NAME VARCHAR(255) COMMENT '商品名称(快照)',
  PN_CODE     VARCHAR(64) COMMENT 'PN料号',
  QUANTITY    INT NOT NULL COMMENT '采购数量',
  UNIT_PRICE  DECIMAL(12,2) COMMENT '采购单价',
  SUBTOTAL    DECIMAL(12,2) COMMENT '小计',
  KEY idx_order_item (ORDER_ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='采购单明细表';

-- -------------------------------------------
-- 六、销售管理
-- -------------------------------------------

-- T_ORDER: 销售订单主表
DROP TABLE IF EXISTS T_ORDER;
CREATE TABLE T_ORDER (
  ORDER_ID        VARCHAR(32) PRIMARY KEY COMMENT '订单ID',
  ORDER_NO       VARCHAR(64) NOT NULL UNIQUE COMMENT '订单编号',
  STORE_ID       VARCHAR(32) NOT NULL COMMENT '销售门店',
  CREATE_USER   VARCHAR(64) COMMENT '制单人',
  CUSTOMER_NAME  VARCHAR(64) COMMENT '客户姓名',
  CUSTOMER_PHONE VARCHAR(32) COMMENT '客户电话',
  CUSTOMER_SOURCE VARCHAR(64) COMMENT '客户来源',
  TOTAL_AMOUNT   DECIMAL(12,2) NOT NULL DEFAULT 0 COMMENT '订单总金额',
  DISCOUNT_AMOUNT DECIMAL(12,2) DEFAULT 0 COMMENT '优惠金额',
  NATIONAL_SUBSIDY DECIMAL(12,2) DEFAULT 0 COMMENT '国补',
  EDUCATION_SUBSIDY DECIMAL(12,2) DEFAULT 0 COMMENT '教育补贴',
  ACTUAL_PAYMENT DECIMAL(12,2) NOT NULL DEFAULT 0 COMMENT '实际收款',
  INVOICE_STATUS VARCHAR(32) DEFAULT '不开票' COMMENT '开票状态',
  ORDER_STATUS   VARCHAR(32) DEFAULT 'completed' COMMENT '订单状态',
  SUBSIDY_STATUS VARCHAR(32) COMMENT '补贴状态',
  SUBSIDY_PERSON VARCHAR(64) COMMENT '补贴人姓名',
  SUBSIDY_ID    VARCHAR(32) COMMENT '补贴人ID',
  REMARK         TEXT COMMENT '备注',
  CREATE_TIME    TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  UPDATE_TIME    TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  IS_DELETED     TINYINT(1) DEFAULT 0,
  KEY idx_order_store (STORE_ID),
  KEY idx_order_no (ORDER_NO),
  KEY idx_order_time (CREATE_TIME)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='销售订单主表';

-- T_ORDER_ITEM: 订单明细表
DROP TABLE IF EXISTS T_ORDER_ITEM;
CREATE TABLE T_ORDER_ITEM (
  ITEM_ID      BIGINT(20) AUTO_INCREMENT PRIMARY KEY,
  ORDER_ID     VARCHAR(32) NOT NULL,
  PRODUCT_ID   VARCHAR(32) NOT NULL COMMENT '商品ID',
  PRODUCT_NAME VARCHAR(255) COMMENT '商品名称(快照)',
  PN_CODE     VARCHAR(64) COMMENT 'PN料号(快照)',
  SN_ID       VARCHAR(32) COMMENT 'SN序列号ID',
  SN_CODE     VARCHAR(128) COMMENT 'SN序列号(快照)',
  IMEI1       VARCHAR(32) COMMENT 'IMEI1(快照)',
  IMEI2       VARCHAR(32) COMMENT 'IMEI2(快照)',
  SALE_PRICE  DECIMAL(12,2) NOT NULL COMMENT '销售单价',
  QUANTITY    INT NOT NULL DEFAULT 1 COMMENT '数量',
  SUBTOTAL    DECIMAL(12,2) NOT NULL COMMENT '小计',
  KEY idx_order_item (ORDER_ID),
  KEY idx_product_item (PRODUCT_ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='订单明细表';

-- T_ORDER_PAYMENT: 订单支付记录表
DROP TABLE IF EXISTS T_ORDER_PAYMENT;
CREATE TABLE T_ORDER_PAYMENT (
  PAYMENT_ID    BIGINT(20) AUTO_INCREMENT PRIMARY KEY,
  ORDER_ID     VARCHAR(32) NOT NULL COMMENT '订单ID',
  PAYMENT_METHOD VARCHAR(64) NOT NULL COMMENT '支付方式',
  AMOUNT       DECIMAL(12,2) NOT NULL COMMENT '支付金额',
  PAYMENT_TIME TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  KEY idx_order_payment (ORDER_ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='订单支付记录表';

-- T_ORDER_ATTACHMENT: 订单附件表
DROP TABLE IF EXISTS T_ORDER_ATTACHMENT;
CREATE TABLE T_ORDER_ATTACHMENT (
  ATTACH_ID   BIGINT(20) AUTO_INCREMENT PRIMARY KEY,
  ORDER_ID   VARCHAR(32) NOT NULL,
  ATTACH_TYPE VARCHAR(64) COMMENT '附件类型:subsidy_photo-补贴照片,product_photo-商品照片',
  FILE_URL   VARCHAR(1024) NOT NULL COMMENT '文件URL',
  CREATE_TIME TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  KEY idx_attach_order (ORDER_ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='订单附件表';

-- -------------------------------------------
-- 七、库房操作
-- -------------------------------------------

-- T_INBOUND: 入库单主表
DROP TABLE IF EXISTS T_INBOUND;
CREATE TABLE T_INBOUND (
  INBOUND_ID   VARCHAR(32) PRIMARY KEY COMMENT '入库单ID',
  INBOUND_NO  VARCHAR(64) NOT NULL UNIQUE COMMENT '入库单号',
  STORE_ID    VARCHAR(32) NOT NULL COMMENT '收货门店',
  SOURCE_TYPE VARCHAR(32) COMMENT '来源类型:purchase-采购入库,return-退货入库,transfer-调拨入库',
  SOURCE_NO   VARCHAR(64) COMMENT '来源单号',
  TOTAL_AMOUNT DECIMAL(12,2) COMMENT '入库总金额',
  TOTAL_QUANTITY INT COMMENT '入库总数量',
  STATUS      VARCHAR(32) DEFAULT 'pending' COMMENT '状态:pending-待入库,partial-部分入库,completed-已完成',
  CREATE_USER VARCHAR(64) COMMENT '制单人',
  CREATE_TIME TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  UPDATE_TIME TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  KEY idx_inbound_store (STORE_ID),
  KEY idx_inbound_no (INBOUND_NO)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='入库单主表';

-- T_INBOUND_ITEM: 入库明细表
DROP TABLE IF EXISTS T_INBOUND_ITEM;
CREATE TABLE T_INBOUND_ITEM (
  ITEM_ID     BIGINT(20) AUTO_INCREMENT PRIMARY KEY,
  INBOUND_ID  VARCHAR(32) NOT NULL,
  PRODUCT_ID  VARCHAR(32) NOT NULL,
  PRODUCT_NAME VARCHAR(255) COMMENT '商品名称(快照)',
  PN_CODE    VARCHAR(64) COMMENT 'PN料号',
  SN_ID      VARCHAR(32) COMMENT 'SN ID(入库后生成)',
  SN_CODE    VARCHAR(128) COMMENT 'SN序列号',
  UNIT_PRICE DECIMAL(12,2) COMMENT '入库单价',
  QUANTITY   INT NOT NULL DEFAULT 1 COMMENT '数量',
  KEY idx_inbound_item (INBOUND_ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='入库明细表';

-- T_OUTBOUND: 出库单主表
DROP TABLE IF EXISTS T_OUTBOUND;
CREATE TABLE T_OUTBOUND (
  OUTBOUND_ID  VARCHAR(32) PRIMARY KEY COMMENT '出库单ID',
  OUTBOUND_NO VARCHAR(64) NOT NULL UNIQUE COMMENT '出库单号',
  STORE_ID   VARCHAR(32) NOT NULL COMMENT '出库门店',
  DEST_STORE_ID VARCHAR(32) COMMENT '目标门店(调拨时)',
  OUT_TYPE  VARCHAR(32) COMMENT '出库类型:sale-销售出库,return-退货出库,transfer-调拨出库,loss-报损',
  SOURCE_ORDER_NO VARCHAR(64) COMMENT '来源单号',
  TOTAL_QUANTITY INT COMMENT '出库总数量',
  STATUS     VARCHAR(32) DEFAULT 'pending' COMMENT '状态:pending-待出库,completed-已完成',
  CREATE_USER VARCHAR(64) COMMENT '制单人',
  CREATE_TIME TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  UPDATE_TIME TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  KEY idx_outbound_store (STORE_ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='出库单主表';

-- T_OUTBOUND_ITEM: 出库明细表
DROP TABLE IF EXISTS T_OUTBOUND_ITEM;
CREATE TABLE T_OUTBOUND_ITEM (
  ITEM_ID     BIGINT(20) AUTO_INCREMENT PRIMARY KEY,
  OUTBOUND_ID VARCHAR(32) NOT NULL,
  PRODUCT_ID  VARCHAR(32) NOT NULL,
  SN_ID      VARCHAR(32) COMMENT 'SN ID',
  SN_CODE    VARCHAR(128) COMMENT 'SN序列号',
  QUANTITY   INT NOT NULL DEFAULT 1,
  KEY idx_outbound_item (OUTBOUND_ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='出库明细表';

-- T_TRANSFER: 调拨单主表
DROP TABLE IF EXISTS T_TRANSFER;
CREATE TABLE T_TRANSFER (
  TRANSFER_ID  VARCHAR(32) PRIMARY KEY COMMENT '调拨单ID',
  TRANSFER_NO VARCHAR(64) NOT NULL UNIQUE COMMENT '调拨单号',
  FROM_STORE_ID VARCHAR(32) NOT NULL COMMENT '调出门店',
  TO_STORE_ID   VARCHAR(32) NOT NULL COMMENT '调入门店',
  TOTAL_QUANTITY INT COMMENT '调拨总数量',
  STATUS     VARCHAR(32) DEFAULT 'pending' COMMENT '状态:pending-待发货,shipping-发货中,received-已收货,completed-已完成',
  APPLY_USER  VARCHAR(64) COMMENT '申请人',
  CONFIRM_USER VARCHAR(64) COMMENT '确认人',
  CREATE_TIME TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  UPDATE_TIME TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  KEY idx_transfer_from (FROM_STORE_ID),
  KEY idx_transfer_to (TO_STORE_ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='调拨单主表';

-- T_TRANSFER_ITEM: 调拨明细表
DROP TABLE IF EXISTS T_TRANSFER_ITEM;
CREATE TABLE T_TRANSFER_ITEM (
  ITEM_ID     BIGINT(20) AUTO_INCREMENT PRIMARY KEY,
  TRANSFER_ID VARCHAR(32) NOT NULL,
  PRODUCT_ID  VARCHAR(32) NOT NULL,
  SN_ID      VARCHAR(32) COMMENT 'SN ID',
  SN_CODE    VARCHAR(128) COMMENT 'SN序列号',
  QUANTITY   INT NOT NULL DEFAULT 1,
  KEY idx_transfer_item (TRANSFER_ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='调拨明细表';

-- -------------------------------------------
-- 八、财务管理
-- -------------------------------------------

-- T_DAILY_STATEMENT: 门店日结表
DROP TABLE IF EXISTS T_DAILY_STATEMENT;
CREATE TABLE T_DAILY_STATEMENT (
  STATEMENT_ID VARCHAR(32) PRIMARY KEY COMMENT '日结单ID',
  STORE_ID    VARCHAR(32) NOT NULL COMMENT '门店ID',
  STATEMENT_DATE DATE NOT NULL COMMENT '日结日期',
  TOTAL_REVENUE DECIMAL(12,2) DEFAULT 0 COMMENT '当日总收入',
  TOTAL_ORDER_COUNT INT DEFAULT 0 COMMENT '当日订单数',
  CASH_AMOUNT  DECIMAL(12,2) DEFAULT 0 COMMENT '现金收款',
  WECHAT_AMOUNT DECIMAL(12,2) DEFAULT 0 COMMENT '微信收款',
  ALIPAY_AMOUNT DECIMAL(12,2) DEFAULT 0 COMMENT '支付宝收款',
  OTHER_AMOUNT DECIMAL(12,2) DEFAULT 0 COMMENT '其他收款',
  DIFFERENCE   DECIMAL(12,2) DEFAULT 0 COMMENT '差异',
  STATUS      VARCHAR(32) DEFAULT 'draft' COMMENT '状态:draft-草稿,submitted-已提交,confirmed-已确认',
  SUBMIT_STAFF VARCHAR(64) COMMENT '提交人',
  CONFIRM_STAFF VARCHAR(64) COMMENT '确认人',
  CREATE_TIME TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  UPDATE_TIME TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  UNIQUE KEY uni_store_date (STORE_ID, STATEMENT_DATE)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='门店日结表';

-- T_EXPENSE: 支出记录表
DROP TABLE IF EXISTS T_EXPENSE;
CREATE TABLE T_EXPENSE (
  EXPENSE_ID  VARCHAR(32) PRIMARY KEY COMMENT '支出ID',
  EXPENSE_NO VARCHAR(64) NOT NULL UNIQUE COMMENT '支出编号',
  STORE_ID   VARCHAR(32) NOT NULL COMMENT '门店ID',
  EXPENSE_TYPE VARCHAR(32) NOT NULL COMMENT '支出类型:purchase-采购付款,operating-运营费用,other-其他',
  AMOUNT     DECIMAL(12,2) NOT NULL COMMENT '支出金额',
  PAYMENT_METHOD VARCHAR(64) COMMENT '支付方式',
  RELATED_ORDER_NO VARCHAR(64) COMMENT '关联单号',
  REMARK     VARCHAR(512) COMMENT '备注',
  CREATE_USER VARCHAR(64) COMMENT '制单人',
  CREATE_TIME TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  UPDATE_TIME TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  IS_DELETED  TINYINT(1) DEFAULT 0,
  KEY idx_expense_store (STORE_ID),
  KEY idx_expense_type (EXPENSE_TYPE)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='支出记录表';

-- -------------------------------------------
-- 九、字典表
-- -------------------------------------------

-- T_DICT_CUSTOMER_SOURCE: 客户来源字典
DROP TABLE IF EXISTS T_DICT_CUSTOMER_SOURCE;
CREATE TABLE T_DICT_CUSTOMER_SOURCE (
  SOURCE_ID   VARCHAR(64) PRIMARY KEY,
  PARENT_ID  VARCHAR(64) COMMENT '父级ID',
  NAME       VARCHAR(128) NOT NULL COMMENT '来源名称',
  LEVEL      INT DEFAULT 1 COMMENT '层级',
  SORT_ORDER INT DEFAULT 0,
  STATUS     TINYINT DEFAULT 1,
  CREATE_TIME TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  UPDATE_TIME TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='客户来源字典';

-- T_DICT_PAYMENT_METHOD: 支付方式字典
DROP TABLE IF EXISTS T_DICT_PAYMENT_METHOD;
CREATE TABLE T_DICT_PAYMENT_METHOD (
  METHOD_ID  VARCHAR(64) PRIMARY KEY,
  NAME      VARCHAR(128) NOT NULL COMMENT '支付方式名称',
  CODE      VARCHAR(64) NOT NULL UNIQUE COMMENT '支付方式代码',
  ICON      VARCHAR(64) COMMENT '图标',
  SORT_ORDER INT DEFAULT 0,
  STATUS    TINYINT DEFAULT 1,
  CREATE_TIME TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  UPDATE_TIME TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='支付方式字典';

-- T_DICT_SUPPLEMENT_ITEM: 附加服务费字典
DROP TABLE IF EXISTS T_DICT_SUPPLEMENT_ITEM;
CREATE TABLE T_DICT_SUPPLEMENT_ITEM (
  ITEM_ID    VARCHAR(64) PRIMARY KEY,
  NAME      VARCHAR(128) NOT NULL COMMENT '项目名称',
  AMOUNT    DECIMAL(10,2) DEFAULT 0 COMMENT '默认金额',
  IS_ACTIVE TINYINT(1) DEFAULT 1,
  SORT_ORDER INT DEFAULT 0,
  CREATE_TIME TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  UPDATE_TIME TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='附加服务费字典';

-- -------------------------------------------
-- 十、初始化数据
-- -------------------------------------------

-- 插入区域
INSERT INTO T_REGION (REGION_ID, REGION_CODE, NAME, SORT_ORDER) VALUES
('R001', 'CD', '成都区域', 1),
('R002', 'CQ', '重庆区域', 2),
('R003', 'DS', '地市区域', 3);

-- 插入角色
INSERT INTO T_ROLE (ROLE_ID, ROLE_CODE, NAME, DESCRIPTION, IS_SYSTEM) VALUES
('RL001', 'boss', '老板', '超级管理员，可查看所有数据', 1),
('RL002', 'finance', '财务', '财务管理人员', 1),
('RL003', 'purchase', '采购', '采购管理人员', 1),
('RL004', 'store_manager', '店长', '门店管理者', 1),
('RL005', 'staff', '店员', '普通店员', 1);

-- 插入支付方式
INSERT INTO T_DICT_PAYMENT_METHOD (METHOD_ID, NAME, CODE, ICON, SORT_ORDER) VALUES
('PM001', '微信支付', 'wechat', 'wechat-icon', 1),
('PM002', '支付宝', 'alipay', 'alipay-icon', 2),
('PM003', '现金', 'cash', 'cash-icon', 3),
('PM004', '银行卡', 'bankcard', 'bankcard-icon', 4),
('PM005', '其他', 'other', 'other-icon', 5);

-- 插入菜单（权限模块）
INSERT INTO T_MENU (MENU_ID, MENU_CODE, NAME, PARENT_ID, MENU_TYPE, PATH, SORT_ORDER) VALUES
-- 一级菜单
('M001', 'dashboard', '工作台', NULL, 'menu', '/dashboard', 1),
('M002', 'sales', '销售管理', NULL, 'module', '/sales', 2),
('M003', 'inventory', '库房管理', NULL, 'module', '/inventory', 3),
('M004', 'purchase', '采购管理', NULL, 'module', '/purchase', 4),
('M005', 'finance', '财务管理', NULL, 'module', '/finance', 5),
('M006', 'product', '商品管理', NULL, 'module', '/product', 6),
('M007', 'store', '门店管理', NULL, 'module', '/store', 7),
('M008', 'system', '系统管理', NULL, 'module', '/system', 8),
-- 销售管理子菜单
('M201', 'sales_order', '销售订单', 'M002', 'menu', '/sales/order', 1),
('M202', 'sales_return', '退货管理', 'M002', 'menu', '/sales/return', 2),
('M203', 'sales_stats', '销售统计', 'M002', 'menu', '/sales/stats', 3),
-- 库房管理子菜单
('M301', 'inventory_sn', '序列号管理', 'M003', 'menu', '/inventory/sn', 1),
('M302', 'inventory_transfer', '调拨管理', 'M003', 'menu', '/inventory/transfer', 2),
('M303', 'inventory_warning', '库存预警', 'M003', 'menu', '/inventory/warning', 3),
('M304', 'inventory_location', '库位管理', 'M003', 'menu', '/inventory/location', 4),
-- 采购管理子菜单
('M401', 'purchase_request', '采购申请', 'M004', 'menu', '/purchase/request', 1),
('M402', 'purchase_order', '采购单', 'M004', 'menu', '/purchase/order', 2),
('M403', 'purchase_inbound', '采购入库', 'M004', 'menu', '/purchase/inbound', 3),
('M404', 'purchase_supplier', '供应商管理', 'M004', 'menu', '/purchase/supplier', 4),
-- 财务管理子菜单
('M501', 'finance_daily', '日结管理', 'M005', 'menu', '/finance/daily', 1),
('M502', 'finance_expense', '支出管理', 'M005', 'menu', '/finance/expense', 2),
('M503', 'finance_report', '财务报表', 'M005', 'menu', '/finance/report', 3),
-- 商品管理子菜单
('M601', 'product_list', '商品列表', 'M006', 'menu', '/product/list', 1),
('M602', 'product_category', '类别管理', 'M006', 'menu', '/product/category', 2),
-- 系统管理子菜单
('M801', 'system_user', '用户管理', 'M008', 'menu', '/system/user', 1),
('M802', 'system_role', '角色管理', 'M008', 'menu', '/system/role', 2),
('M803', 'system_menu', '菜单管理', 'M008', 'menu', '/system/menu', 3),
('M804', 'system_region', '区域管理', 'M008', 'menu', '/system/region', 4);

-- 给老板角色分配所有菜单
INSERT INTO T_ROLE_MENU (ROLE_ID, MENU_ID)
SELECT 'RL001', MENU_ID FROM T_MENU WHERE STATUS = 1;

-- 给财务角色分配财务和销售相关菜单
INSERT INTO T_ROLE_MENU (ROLE_ID, MENU_ID)
SELECT 'RL002', MENU_ID FROM T_MENU WHERE MENU_CODE IN ('dashboard', 'sales', 'finance', 'M201', 'M202', 'M203', 'M501', 'M502', 'M503');

-- 给采购角色分配采购和库存菜单
INSERT INTO T_ROLE_MENU (ROLE_ID, MENU_ID)
SELECT 'RL003', MENU_ID FROM T_MENU WHERE MENU_CODE IN ('dashboard', 'inventory', 'purchase', 'M301', 'M302', 'M303', 'M304', 'M401', 'M402', 'M403', 'M404');

-- 给店长角色分配门店相关菜单
INSERT INTO T_ROLE_MENU (ROLE_ID, MENU_ID)
SELECT 'RL004', MENU_ID FROM T_MENU WHERE MENU_CODE IN ('dashboard', 'sales', 'inventory', 'finance', 'M201', 'M202', 'M203', 'M301', 'M302', 'M303', 'M304', 'M501', 'M502', 'M503');

-- 给店员角色分配基础菜单
INSERT INTO T_ROLE_MENU (ROLE_ID, MENU_ID)
SELECT 'RL005', MENU_ID FROM T_MENU WHERE MENU_CODE IN ('dashboard', 'sales', 'M201', 'M202');

SET FOREIGN_KEY_CHECKS = 1;

-- ==========================================
-- 初始化完成
-- ==========================================
