-- ==========================================
-- ANY-ERP 数据库初始化脚本 v1.0
-- ==========================================

SET NAMES utf8mb4;
SET FOREIGN_KEY_CHECKS = 0;

-- -------------------------------------------
-- 一、组织架构
-- -------------------------------------------

-- T_REGION: 区域表
DROP TABLE IF EXISTS T_REGION;
CREATE TABLE T_REGION (
  REGION_ID     VARCHAR(32) PRIMARY KEY COMMENT '区域ID',
  REGION_CODE   VARCHAR(32) NOT NULL UNIQUE COMMENT '区域代码(CD/CQ/DS)',
  NAME          VARCHAR(128) NOT NULL COMMENT '区域名称',
  SORT_ORDER    INT DEFAULT 0 COMMENT '排序',
  STATUS        TINYINT DEFAULT 1 COMMENT '状态：1-启用，0-停用',
  CREATE_TIME   TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  UPDATE_TIME   TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='区域表';

-- T_DISTRIBUTOR: 经销商/股东表
DROP TABLE IF EXISTS T_DISTRIBUTOR;
CREATE TABLE T_DISTRIBUTOR (
  DISTRIBUTOR_ID VARCHAR(32) PRIMARY KEY COMMENT '经销商ID',
  REGION_ID      VARCHAR(32) COMMENT '所属区域',
  NAME           VARCHAR(255) NOT NULL COMMENT '名称',
  EQUITY_RATIO  DECIMAL(5,2) COMMENT '股权比例(%)',
  PHONE         VARCHAR(32) COMMENT '联系电话',
  ADDRESS       VARCHAR(512) COMMENT '地址',
  STATUS        TINYINT DEFAULT 1 COMMENT '状态：1-正常，0-停用',
  CREATE_TIME   TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  UPDATE_TIME   TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  IS_DELETED    TINYINT(1) DEFAULT 0,
  KEY idx_region (REGION_ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='经销商/股东表';

-- T_STORE: 门店表
DROP TABLE IF EXISTS T_STORE;
CREATE TABLE T_STORE (
  STORE_ID      VARCHAR(32) PRIMARY KEY COMMENT '门店ID',
  DISTRIBUTOR_ID VARCHAR(32) COMMENT '所属经销商',
  REGION_ID     VARCHAR(32) COMMENT '所属区域',
  MANAGER_STAFF_ID BIGINT(20) COMMENT '门店店长员工ID',
  NAME          VARCHAR(255) NOT NULL COMMENT '门店名称',
  ADDRESS       VARCHAR(512) COMMENT '门店地址',
  PHONE         VARCHAR(32) COMMENT '门店电话',
  STATUS        TINYINT DEFAULT 1 COMMENT '状态：1-正常，0-停用',
  CREATE_TIME   TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  UPDATE_TIME   TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  IS_DELETED    TINYINT(1) DEFAULT 0,
  KEY idx_distributor (DISTRIBUTOR_ID),
  KEY idx_region (REGION_ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='门店表';

-- T_STAFF: 员工表
DROP TABLE IF EXISTS T_STAFF;
CREATE TABLE T_STAFF (
  STAFF_ID      BIGINT(20) AUTO_INCREMENT PRIMARY KEY COMMENT '员工ID',
  DISTRIBUTOR_ID VARCHAR(32) NOT NULL COMMENT '所属经销商',
  STORE_ID      VARCHAR(32) COMMENT '所属门店',
  SUPERVISOR_STAFF_ID BIGINT(20) COMMENT '直属上级员工ID',
  REGION_ID     VARCHAR(32) COMMENT '所属区域',
  NAME          VARCHAR(64) NOT NULL COMMENT '员工姓名',
  PHONE         VARCHAR(32) NOT NULL COMMENT '手机号(登录账号)',
  PASSWORD_HASH VARCHAR(128) COMMENT '密码哈希',
  ROLE_CODE     VARCHAR(32) DEFAULT 'staff' COMMENT '角色代码',
  STATUS        TINYINT DEFAULT 1 COMMENT '状态：1-正常，0-停用',
  CREATE_TIME   TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  UPDATE_TIME   TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  IS_DELETED    TINYINT(1) DEFAULT 0,
  UNIQUE KEY uni_phone (PHONE),
  KEY idx_distributor (DISTRIBUTOR_ID),
  KEY idx_store (STORE_ID),
  KEY idx_region (REGION_ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='员工表';

-- -------------------------------------------
-- 二、权限管理
-- -------------------------------------------

-- T_MENU: 菜单表
DROP TABLE IF EXISTS T_MENU;
CREATE TABLE T_MENU (
  MENU_ID       VARCHAR(32) PRIMARY KEY COMMENT '菜单ID',
  MENU_CODE    VARCHAR(64) NOT NULL UNIQUE COMMENT '菜单代码',
  NAME         VARCHAR(128) NOT NULL COMMENT '菜单名称',
  PARENT_ID    VARCHAR(32) COMMENT '父级菜单ID',
  MENU_TYPE    VARCHAR(16) COMMENT '类型：module-模块，menu-菜单，button-按钮',
  PATH         VARCHAR(256) COMMENT '路由路径',
  ICON         VARCHAR(64) COMMENT '图标',
  SORT_ORDER   INT DEFAULT 0,
  STATUS       TINYINT DEFAULT 1,
  CREATE_TIME  TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  UPDATE_TIME  TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='菜单表';

-- T_ROLE: 角色表
DROP TABLE IF EXISTS T_ROLE;
CREATE TABLE T_ROLE (
  ROLE_ID       VARCHAR(32) PRIMARY KEY COMMENT '角色ID',
  ROLE_CODE    VARCHAR(64) NOT NULL UNIQUE COMMENT '角色代码',
  NAME         VARCHAR(128) NOT NULL COMMENT '角色名称',
  DESCRIPTION  VARCHAR(512) COMMENT '描述',
  IS_SYSTEM    TINYINT(1) DEFAULT 0 COMMENT '是否系统角色',
  STATUS       TINYINT DEFAULT 1,
  CREATE_TIME  TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  UPDATE_TIME  TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='角色表';

-- T_ROLE_MENU: 角色菜单关联表
DROP TABLE IF EXISTS T_ROLE_MENU;
CREATE TABLE T_ROLE_MENU (
  ID          BIGINT(20) AUTO_INCREMENT PRIMARY KEY,
  ROLE_ID     VARCHAR(32) NOT NULL,
  MENU_ID     VARCHAR(32) NOT NULL,
  CREATE_TIME TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  UNIQUE KEY uni_role_menu (ROLE_ID, MENU_ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='角色菜单关联表';

-- T_STAFF_ROLE: 员工角色关联表
DROP TABLE IF EXISTS T_STAFF_ROLE;
CREATE TABLE T_STAFF_ROLE (
  ID          BIGINT(20) AUTO_INCREMENT PRIMARY KEY,
  STAFF_ID    BIGINT(20) NOT NULL,
  ROLE_ID     VARCHAR(32) NOT NULL,
  CREATE_TIME TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  UNIQUE KEY uni_staff_role (STAFF_ID, ROLE_ID),
  KEY idx_staff (STAFF_ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='员工角色关联表';

-- T_STAFF_STORE_PERMISSION: 员工可访问门店（默认不自动分配）
DROP TABLE IF EXISTS T_STAFF_STORE_PERMISSION;
CREATE TABLE T_STAFF_STORE_PERMISSION (
  ID          BIGINT(20) AUTO_INCREMENT PRIMARY KEY,
  STAFF_ID    BIGINT(20) NOT NULL,
  STORE_ID    VARCHAR(32) NOT NULL,
  CREATE_TIME TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  UNIQUE KEY uk_staff_store (STAFF_ID, STORE_ID),
  KEY idx_staff_store_store (STORE_ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='员工可访问门店';

-- T_REGION_PERMISSION: 区域数据权限表
DROP TABLE IF EXISTS T_REGION_PERMISSION;
CREATE TABLE T_REGION_PERMISSION (
  ID           BIGINT(20) AUTO_INCREMENT PRIMARY KEY,
  STAFF_ID     VARCHAR(32) NOT NULL COMMENT '员工ID',
  REGION_CODE  VARCHAR(32) NOT NULL COMMENT '区域代码',
  CAN_VIEW     TINYINT(1) DEFAULT 1 COMMENT '可查看',
  CAN_MANAGE   TINYINT(1) DEFAULT 0 COMMENT '可管理',
  CREATE_TIME  TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  KEY idx_staff (STAFF_ID),
  KEY idx_region (REGION_CODE)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='区域数据权限表';

-- -------------------------------------------
-- 三、商品模块
-- -------------------------------------------

-- T_PRODUCT: 商品主表
DROP TABLE IF EXISTS T_PRODUCT;
CREATE TABLE T_PRODUCT (
  PRODUCT_ID      VARCHAR(32) PRIMARY KEY COMMENT '商品ID',
  PRODUCT_CODE    VARCHAR(32) NOT NULL UNIQUE COMMENT '商品编号(P+日期+序号)',
  NAME            VARCHAR(255) NOT NULL COMMENT '商品名称',
  CATEGORY        VARCHAR(64) COMMENT '产品类别',
  MANUFACTURER_CODE VARCHAR(64) COMMENT '厂商编码',
  BARCODE_69      VARCHAR(64) COMMENT '69码',
  NEED_SN         TINYINT(1) DEFAULT 0 COMMENT '是否需要SN',
  NEED_IMEI       TINYINT(1) DEFAULT 0 COMMENT '是否需要IMEI',
  STANDARD_PRICE  DECIMAL(12,2) COMMENT '标准售价',
  MIN_SALE_PRICE  DECIMAL(12,2) COMMENT '最低销售限价',
  UNIT            VARCHAR(16) DEFAULT '台' COMMENT '单位',
  SPECS_JSON      JSON COMMENT '规格参数(颜色/容量/版本等)',
  REMARK          VARCHAR(512) COMMENT '备注',
  IS_FOCUS_PRODUCT TINYINT(1) NOT NULL DEFAULT 0 COMMENT '是否属于经营看板重点产品',
  STATUS          TINYINT DEFAULT 1 COMMENT '状态：1-启用，0-停用',
  CREATE_TIME     TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  UPDATE_TIME     TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  IS_DELETED      TINYINT(1) DEFAULT 0,
  KEY idx_product_code (PRODUCT_CODE),
  KEY idx_category (CATEGORY),
  KEY idx_product_focus (IS_FOCUS_PRODUCT, IS_DELETED, STATUS),
  KEY idx_name (NAME)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='商品主表';

DROP TABLE IF EXISTS T_PRODUCT_APPLICATION;
CREATE TABLE T_PRODUCT_APPLICATION (
  APPLICATION_ID      VARCHAR(32) PRIMARY KEY COMMENT '申请ID',
  APPLICATION_NO      VARCHAR(64) NOT NULL UNIQUE COMMENT '申请单号',
  PRODUCT_NAME        VARCHAR(255) NOT NULL COMMENT '拟新建商品名称',
  CATEGORY_ID         VARCHAR(32) COMMENT '商品分类ID',
  CATEGORY_NAME       VARCHAR(512) COMMENT '商品分类路径',
  PAYLOAD_JSON        JSON NOT NULL COMMENT '商品创建参数快照',
  APPLICANT_STAFF_ID  BIGINT NOT NULL COMMENT '申请人员工ID',
  APPLICANT_NAME      VARCHAR(64) NOT NULL COMMENT '申请人姓名',
  DISTRIBUTOR_ID      VARCHAR(32) COMMENT '所属经销商',
  STATUS              VARCHAR(32) DEFAULT 'pending' COMMENT 'pending/approved/rejected',
  REVIEW_STAFF_ID     BIGINT COMMENT '审批人员工ID',
  REVIEW_USER_NAME    VARCHAR(64) COMMENT '审批人姓名',
  REVIEW_COMMENT      VARCHAR(512) COMMENT '审批意见',
  REVIEW_TIME         DATETIME COMMENT '审批时间',
  PRODUCT_ID          VARCHAR(32) COMMENT '审批后生成的商品ID',
  CREATE_TIME         TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  UPDATE_TIME         TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  KEY idx_product_application_status (STATUS, CREATE_TIME),
  KEY idx_product_application_applicant (APPLICANT_STAFF_ID, CREATE_TIME),
  KEY idx_product_application_distributor (DISTRIBUTOR_ID, CREATE_TIME)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='新建商品审批申请';

-- T_PRODUCT_PN: 商品PN料号表
DROP TABLE IF EXISTS T_PRODUCT_PN;
CREATE TABLE T_PRODUCT_PN (
  PN_ID        VARCHAR(32) PRIMARY KEY COMMENT 'PN ID',
  PRODUCT_ID   VARCHAR(32) NOT NULL COMMENT '关联商品ID',
  PN_CODE      VARCHAR(64) NOT NULL COMMENT 'PN料号',
  BARCODE      VARCHAR(64) COMMENT '条形码(69码)',
  IS_PRIMARY   TINYINT(1) DEFAULT 0 COMMENT '是否主料号',
  STATUS       TINYINT DEFAULT 1,
  CREATE_TIME  TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  UPDATE_TIME  TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  IS_DELETED   TINYINT(1) DEFAULT 0,
  UNIQUE KEY uni_pn_code (PN_CODE),
  KEY idx_product_pn (PRODUCT_ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='商品PN料号表';

-- T_PRODUCT_SN: 商品序列号表
DROP TABLE IF EXISTS T_PRODUCT_SN;
CREATE TABLE T_PRODUCT_SN (
  SN_ID         VARCHAR(32) PRIMARY KEY COMMENT 'SN ID',
  PRODUCT_ID    VARCHAR(32) NOT NULL COMMENT '关联商品ID',
  PN_ID         VARCHAR(32) COMMENT '关联PN ID',
  SN_CODE       VARCHAR(128) NOT NULL COMMENT '序列号',
  IMEI1         VARCHAR(32) COMMENT 'IMEI1(手机类)',
  IMEI2         VARCHAR(32) COMMENT 'IMEI2(手机类)',
  STATUS        VARCHAR(32) DEFAULT 'in_stock' COMMENT '状态:in_stock-在库,sold-已销售,transferring-调拨中,repair-返修',
  STORE_ID      VARCHAR(32) COMMENT '当前门店',
  LOCATION_ID   VARCHAR(32) COMMENT '当前库位',
  INBOUND_TIME  TIMESTAMP COMMENT '入库时间',
  INBOUND_PRICE DECIMAL(12,2) COMMENT '入库价格',
  ORIGINAL_PICKUP_PRICE DECIMAL(12,2) DEFAULT 0 COMMENT '原始提货价',
  SUPPLIER_ID   VARCHAR(32) COMMENT '采购来源供应商ID',
  SUPPLIER_NAME VARCHAR(255) COMMENT '采购来源供应商名称快照',
  TAX_TYPE      VARCHAR(32) DEFAULT 'UNKNOWN' COMMENT '税务属性:TAX_INCLUDED/UNTAXED/UNKNOWN',
  SOURCE_TYPE   VARCHAR(32) DEFAULT 'OTHER' COMMENT '货源性质',
  BATCH_NO      VARCHAR(64) COMMENT '批次号(FIFO)',
  REMARK        VARCHAR(255) COMMENT '备注',
  CREATE_TIME   TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  UPDATE_TIME   TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  IS_DELETED    TINYINT(1) DEFAULT 0,
  UNIQUE KEY uni_sn_code (SN_CODE),
  KEY idx_product_sn (PRODUCT_ID),
  KEY idx_store_status (STORE_ID, STATUS),
  KEY idx_batch (BATCH_NO)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='商品序列号表';

DROP TABLE IF EXISTS T_INVENTORY_RESOURCE_RIGHT;
CREATE TABLE T_INVENTORY_RESOURCE_RIGHT (
  RIGHT_ID VARCHAR(32) PRIMARY KEY, SN_ID VARCHAR(32) NOT NULL, SN_CODE VARCHAR(128) NOT NULL,
  PRODUCT_ID VARCHAR(32) NOT NULL, RESOURCE_TYPE VARCHAR(32) NOT NULL,
  INITIAL_STATUS VARCHAR(32) NOT NULL DEFAULT 'NOT_APPLICABLE', CURRENT_STATUS VARCHAR(32) NOT NULL DEFAULT 'NOT_APPLICABLE',
  AMOUNT DECIMAL(12,2) DEFAULT 0, SOURCE VARCHAR(128), LOCKED_SOURCE_TYPE VARCHAR(32), LOCKED_SOURCE_ID VARCHAR(32),
  REMARK VARCHAR(512), VERSION INT DEFAULT 0, CREATE_TIME TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  UPDATE_TIME TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  UNIQUE KEY uk_sn_resource (SN_ID, RESOURCE_TYPE), KEY idx_resource_right_sn_code (SN_CODE),
  KEY idx_resource_right_status (RESOURCE_TYPE, CURRENT_STATUS)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='SN资源权益当前状态';

DROP TABLE IF EXISTS T_RESOURCE_CATEGORY;
CREATE TABLE T_RESOURCE_CATEGORY (
  CATEGORY_ID VARCHAR(32) PRIMARY KEY, CATEGORY_CODE VARCHAR(32) NOT NULL, NAME VARCHAR(128) NOT NULL,
  SHORT_NAME VARCHAR(64), DEFAULT_ACCOUNT_ID VARCHAR(64), SUPPORTS_SALE_USE TINYINT(1) DEFAULT 1,
  SUPPORTS_COMPANY_CLAIM TINYINT(1) DEFAULT 1, SORT_ORDER INT DEFAULT 0, STATUS TINYINT(1) DEFAULT 1,
  REMARK VARCHAR(512), CREATE_TIME TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  UPDATE_TIME TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  UNIQUE KEY uk_resource_category_code (CATEGORY_CODE)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='资源权益类别配置';

INSERT INTO T_RESOURCE_CATEGORY (CATEGORY_ID,CATEGORY_CODE,NAME,SHORT_NAME,SUPPORTS_SALE_USE,SUPPORTS_COMPANY_CLAIM,SORT_ORDER,STATUS) VALUES
('RC_GOV_SUBSIDY','GOV_SUBSIDY','国补资格','国补',1,1,10,1),
('RC_EDU_SUBSIDY','EDU_SUBSIDY','教育补贴资格','教育补贴',1,1,20,1),
('RC_SALES_REPORT','SALES_REPORT','销量报号资格','销量报号',1,1,30,1),
('RC_MANUFACTURER_REBATE','MANUFACTURER_REBATE','厂商返利','厂商返利',0,0,40,1),
('RC_MANUAL_REBATE','MANUAL_REBATE','手工返利','手工返利',0,0,45,1),
('RC_SALES_BONUS','SALES_BONUS','销售红包','销售红包',0,0,50,1),
('RC_SELF_PURCHASE_REPORT','SELF_PURCHASE_REPORT','报号自购','报号自购',1,0,60,1);

DROP TABLE IF EXISTS T_GOODS_TYPE_RESOURCE;
DROP TABLE IF EXISTS T_GOODS_TYPE;
CREATE TABLE T_GOODS_TYPE (
  GOODS_TYPE_ID VARCHAR(32) PRIMARY KEY, NAME VARCHAR(128) NOT NULL,
  SORT_ORDER INT DEFAULT 0, STATUS TINYINT(1) DEFAULT 1, REMARK VARCHAR(512),
  CREATE_TIME TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  UPDATE_TIME TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  UNIQUE KEY uk_goods_type_name (NAME), KEY idx_goods_type_status (STATUS, SORT_ORDER)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='采购货型模板';

CREATE TABLE T_GOODS_TYPE_RESOURCE (
  GOODS_TYPE_ID VARCHAR(32) NOT NULL, CATEGORY_ID VARCHAR(32) NOT NULL,
  SORT_ORDER INT DEFAULT 0, CREATE_TIME TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (GOODS_TYPE_ID, CATEGORY_ID), KEY idx_goods_type_resource_category (CATEGORY_ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='货型包含的资源类别';

INSERT INTO T_GOODS_TYPE (GOODS_TYPE_ID,NAME,SORT_ORDER,STATUS,REMARK) VALUES
('GT_SERVICE_FULL_RESOURCE','服务商全资源货',10,1,'系统初始化的全资源货型模板');

INSERT INTO T_GOODS_TYPE_RESOURCE (GOODS_TYPE_ID,CATEGORY_ID,SORT_ORDER) VALUES
('GT_SERVICE_FULL_RESOURCE','RC_GOV_SUBSIDY',10),
('GT_SERVICE_FULL_RESOURCE','RC_EDU_SUBSIDY',20),
('GT_SERVICE_FULL_RESOURCE','RC_MANUFACTURER_REBATE',30),
('GT_SERVICE_FULL_RESOURCE','RC_SALES_BONUS',40),
('GT_SERVICE_FULL_RESOURCE','RC_SELF_PURCHASE_REPORT',50);

DROP TABLE IF EXISTS T_RESOURCE_RIGHT_CHANGE_ORDER;
CREATE TABLE T_RESOURCE_RIGHT_CHANGE_ORDER (
  CHANGE_ID VARCHAR(32) PRIMARY KEY, CHANGE_ORDER_NO VARCHAR(64) NOT NULL, SN_ID VARCHAR(32) NOT NULL,
  SN_CODE VARCHAR(128) NOT NULL, PRODUCT_ID VARCHAR(32) NOT NULL, RESOURCE_TYPE VARCHAR(32) NOT NULL,
  BEFORE_STATUS VARCHAR(32) NOT NULL, AFTER_STATUS VARCHAR(32) NOT NULL, CHANGE_AMOUNT DECIMAL(12,2) DEFAULT 0,
  CHANGE_REASON VARCHAR(32) NOT NULL, APPROVAL_STATUS VARCHAR(32) DEFAULT 'approved', RELATED_ORDER_ID VARCHAR(32),
  RELATED_SALE_ORDER_ID VARCHAR(32), ATTACHMENT_URL VARCHAR(1000), APPLICANT_STAFF_ID BIGINT,
  APPLICANT_NAME VARCHAR(64), REVIEWER_STAFF_ID BIGINT, REVIEWER_NAME VARCHAR(64), REVIEW_COMMENT VARCHAR(512),
  REVIEW_TIME DATETIME, CREATE_TIME TIMESTAMP DEFAULT CURRENT_TIMESTAMP, REMARK VARCHAR(512),
  UNIQUE KEY uk_resource_change_no (CHANGE_ORDER_NO), KEY idx_resource_change_sn (SN_ID, CREATE_TIME),
  KEY idx_resource_change_approval (APPROVAL_STATUS, CREATE_TIME), KEY idx_resource_change_sale (RELATED_SALE_ORDER_ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='资源权益变更及审批单';

DROP TABLE IF EXISTS T_PRODUCT_RESOURCE_COST_CONFIG;
CREATE TABLE T_PRODUCT_RESOURCE_COST_CONFIG (
  CONFIG_ID VARCHAR(32) PRIMARY KEY, PRODUCT_ID VARCHAR(32) NOT NULL, RESOURCE_TYPE VARCHAR(32) NOT NULL,
  COST_AMOUNT DECIMAL(12,2) NOT NULL DEFAULT 0, STATUS TINYINT(1) DEFAULT 1, REMARK VARCHAR(512),
  CREATE_USER VARCHAR(64), CREATE_TIME TIMESTAMP DEFAULT CURRENT_TIMESTAMP, UPDATE_USER VARCHAR(64),
  UPDATE_TIME TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  UNIQUE KEY uk_product_resource_cost (PRODUCT_ID, RESOURCE_TYPE)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='商品资源类型成本定义';

DROP TABLE IF EXISTS T_INVENTORY_RESOURCE_COST_ADJUSTMENT;
CREATE TABLE T_INVENTORY_RESOURCE_COST_ADJUSTMENT (
  ADJUSTMENT_ID VARCHAR(32) PRIMARY KEY, SN_ID VARCHAR(32) NOT NULL, SN_CODE VARCHAR(128) NOT NULL,
  PRODUCT_ID VARCHAR(32) NOT NULL, RESOURCE_TYPE VARCHAR(32) NOT NULL, ADJUSTMENT_AMOUNT DECIMAL(12,2) NOT NULL,
  BEFORE_PRODUCT_COST DECIMAL(12,2) DEFAULT 0, AFTER_PRODUCT_COST DECIMAL(12,2) DEFAULT 0,
  SOURCE_TYPE VARCHAR(32) NOT NULL, SOURCE_ID VARCHAR(32) NOT NULL, AFFECT_SALES_SETTLEMENT_COST TINYINT(1) DEFAULT 0,
  OPERATOR_ID BIGINT, OPERATOR_NAME VARCHAR(64), CREATE_TIME TIMESTAMP DEFAULT CURRENT_TIMESTAMP, REMARK VARCHAR(512),
  UNIQUE KEY uk_resource_cost_source (SOURCE_TYPE, SOURCE_ID), KEY idx_resource_cost_sn (SN_ID, CREATE_TIME),
  KEY idx_resource_cost_product (PRODUCT_ID, RESOURCE_TYPE)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='产品资源成本调整流水';

DROP TABLE IF EXISTS T_RESOURCE_SETTLEMENT;
CREATE TABLE T_RESOURCE_SETTLEMENT (
  SETTLEMENT_ID VARCHAR(32) PRIMARY KEY, SETTLEMENT_NO VARCHAR(64) NOT NULL,
  SOURCE_TYPE VARCHAR(32) NOT NULL, SOURCE_ID VARCHAR(64) NOT NULL, BATCH_NO VARCHAR(64),
  SN_ID VARCHAR(32), SN_CODE VARCHAR(128), PRODUCT_ID VARCHAR(32),
  RESOURCE_TYPE VARCHAR(32) NOT NULL, COUNTERPARTY_ID VARCHAR(32), COUNTERPARTY_NAME VARCHAR(255),
  AMOUNT DECIMAL(12,2) NOT NULL, MATCHED_AMOUNT DECIMAL(12,2) DEFAULT 0,
  STATUS VARCHAR(32) DEFAULT 'PENDING',
  TARGET_ACCOUNT_ID VARCHAR(64), SETTLED_AT DATETIME, SETTLED_BY BIGINT, SETTLED_BY_NAME VARCHAR(64),
  CREATE_STAFF_ID BIGINT, CREATE_USER VARCHAR(64),
  CANCELLED_AT DATETIME, CANCELLED_BY BIGINT, CANCELLED_BY_NAME VARCHAR(64),
  REVERSED_AT DATETIME, REVERSED_BY BIGINT, REVERSED_BY_NAME VARCHAR(64),
  CORRECTION_REASON VARCHAR(512),
  CREATE_TIME TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  UPDATE_TIME TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  REMARK VARCHAR(512),
  UNIQUE KEY uk_resource_settlement_no (SETTLEMENT_NO),
  UNIQUE KEY uk_resource_settlement_source (SOURCE_TYPE,SOURCE_ID,RESOURCE_TYPE),
  KEY idx_resource_settlement_status (STATUS,CREATE_TIME),
  KEY idx_resource_settlement_sn (SN_ID,RESOURCE_TYPE),
  KEY idx_resource_settlement_counterparty (COUNTERPARTY_ID,CREATE_TIME)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='资源权益待下账及到账记录';

DROP TABLE IF EXISTS T_REBATE_SETTLEMENT_ALLOCATION;
DROP TABLE IF EXISTS T_REBATE_POSTING_ORDER;
DROP TABLE IF EXISTS T_SUPPLIER_REBATE;
CREATE TABLE T_SUPPLIER_REBATE (
  REBATE_ID VARCHAR(32) PRIMARY KEY,
  SUPPLIER_ID VARCHAR(32) NOT NULL,
  SUPPLIER_NAME VARCHAR(255),
  TYPE VARCHAR(32) NOT NULL,
  AMOUNT DECIMAL(12,2) NOT NULL,
  BALANCE DECIMAL(12,2) NOT NULL,
  RELATED_NO VARCHAR(64),
  REMARK VARCHAR(512),
  STATUS VARCHAR(32) DEFAULT 'active',
  SOURCE_TYPE VARCHAR(32) DEFAULT 'manual',
  SOURCE_ID VARCHAR(64),
  REVERSAL_OF VARCHAR(32),
  CREATE_USER VARCHAR(64),
  CREATE_TIME TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  KEY idx_rebate_supplier (SUPPLIER_ID),
  KEY idx_rebate_type (TYPE)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='供应商返利余额流水';

CREATE TABLE T_REBATE_POSTING_ORDER (
  POSTING_ID VARCHAR(32) PRIMARY KEY,
  POSTING_NO VARCHAR(64) NOT NULL,
  SUPPLIER_ID VARCHAR(32),
  SUPPLIER_NAME VARCHAR(255),
  SETTLEMENT_TYPE VARCHAR(32) DEFAULT 'supplier',
  PAYEE_TYPE VARCHAR(32) DEFAULT 'supplier',
  PAYEE_ID VARCHAR(64),
  PAYEE_NAME VARCHAR(255),
  SOURCE_TYPE VARCHAR(32),
  SOURCE_ID VARCHAR(64),
  SOURCE_NO VARCHAR(64),
  POSTING_DATE DATE NOT NULL,
  AMOUNT DECIMAL(12,2) NOT NULL,
  MATCHED_AMOUNT DECIMAL(12,2) DEFAULT 0,
  STATUS VARCHAR(32) DEFAULT 'UNMATCHED',
  REBATE_ID VARCHAR(32),
  CREATE_STAFF_ID BIGINT,
  CREATE_USER VARCHAR(64),
  CREATE_TIME TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  REVERSED_AT DATETIME,
  REVERSED_BY BIGINT,
  REVERSED_BY_NAME VARCHAR(64),
  REVERSAL_REASON VARCHAR(512),
  REMARK VARCHAR(512) NOT NULL,
  UNIQUE KEY uk_rebate_posting_no (POSTING_NO),
  KEY idx_rebate_posting_supplier (SUPPLIER_ID,STATUS,POSTING_DATE),
  KEY idx_rebate_posting_status (STATUS,CREATE_TIME)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='供应商返利预上账单';

CREATE TABLE T_REBATE_SETTLEMENT_ALLOCATION (
  ALLOCATION_ID VARCHAR(32) PRIMARY KEY,
  SETTLEMENT_ID VARCHAR(32) NOT NULL,
  POSTING_ID VARCHAR(32) NOT NULL,
  AMOUNT DECIMAL(12,2) NOT NULL,
  STATUS VARCHAR(32) DEFAULT 'ACTIVE',
  CREATE_STAFF_ID BIGINT,
  CREATE_USER VARCHAR(64),
  CREATE_TIME TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  REVERSED_AT DATETIME,
  REVERSED_BY BIGINT,
  REVERSED_BY_NAME VARCHAR(64),
  REVERSAL_REASON VARCHAR(512),
  KEY idx_rebate_allocation_settlement (SETTLEMENT_ID,STATUS),
  KEY idx_rebate_allocation_posting (POSTING_ID,STATUS)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='返利上账与下账核销分配';

DROP TABLE IF EXISTS T_PRODUCT_PRICE;
CREATE TABLE T_PRODUCT_PRICE (
  PRICE_ID       VARCHAR(32) PRIMARY KEY COMMENT '价格ID',
  PRODUCT_ID     VARCHAR(32) NOT NULL COMMENT '商品ID',
  COST_PRICE     DECIMAL(12,2) DEFAULT 0 COMMENT '库存成本价(加权平均)',
  STANDARD_PRICE DECIMAL(12,2) DEFAULT 0 COMMENT '产品定价(订单毛利商品成本，默认采购价)',
  MIN_SALE_PRICE DECIMAL(12,2) DEFAULT 0 COMMENT '最低售价',
  EFFECTIVE_TIME DATETIME COMMENT '生效时间',
  CREATE_USER    VARCHAR(64) COMMENT '操作人',
  STATUS         TINYINT DEFAULT 1 COMMENT '状态',
  UNIQUE KEY uk_product_price_product (PRODUCT_ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='商品价格表';

DROP TABLE IF EXISTS T_SN_DISTRIBUTOR_PRICE_CHANGE_LOG;
DROP TABLE IF EXISTS T_SN_DISTRIBUTOR_PRICE;
CREATE TABLE T_SN_DISTRIBUTOR_PRICE (
  PRICE_ID VARCHAR(32) PRIMARY KEY COMMENT 'SN特价ID',
  SN_ID VARCHAR(32) NOT NULL COMMENT 'SN记录ID',
  SN_CODE VARCHAR(128) NOT NULL COMMENT 'SN快照',
  DISTRIBUTOR_ID VARCHAR(32) NOT NULL COMMENT '经销商ID',
  SPECIAL_PRICE DECIMAL(12,2) NOT NULL COMMENT 'SN销售特价',
  STATUS TINYINT(1) DEFAULT 1 COMMENT '1生效 0已取消',
  REMARK VARCHAR(512) COMMENT '备注',
  CREATE_STAFF_ID BIGINT COMMENT '创建人员工ID',
  CREATE_USER VARCHAR(64) COMMENT '创建人',
  CREATE_TIME TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  UPDATE_STAFF_ID BIGINT COMMENT '更新人员工ID',
  UPDATE_USER VARCHAR(64) COMMENT '更新人',
  UPDATE_TIME TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  UNIQUE KEY uk_sn_distributor_price (SN_ID, DISTRIBUTOR_ID),
  KEY idx_sn_distributor_price_scope (DISTRIBUTOR_ID, STATUS, UPDATE_TIME),
  KEY idx_sn_distributor_price_sn_code (SN_CODE)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='经销商SN销售特价';

CREATE TABLE T_SN_DISTRIBUTOR_PRICE_CHANGE_LOG (
  CHANGE_ID VARCHAR(32) PRIMARY KEY COMMENT '变更ID',
  PRICE_ID VARCHAR(32) NOT NULL COMMENT 'SN特价ID',
  SN_ID VARCHAR(32) NOT NULL COMMENT 'SN记录ID',
  SN_CODE VARCHAR(128) NOT NULL COMMENT 'SN快照',
  DISTRIBUTOR_ID VARCHAR(32) NOT NULL COMMENT '经销商ID',
  ACTION VARCHAR(32) NOT NULL COMMENT 'SET/UPDATE/CANCEL',
  OLD_PRICE DECIMAL(12,2) COMMENT '变更前价格',
  NEW_PRICE DECIMAL(12,2) COMMENT '变更后价格',
  REMARK VARCHAR(512) COMMENT '调价原因或备注',
  OPERATOR_STAFF_ID BIGINT COMMENT '操作人员工ID',
  OPERATOR_NAME VARCHAR(64) COMMENT '操作人',
  CREATE_TIME TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  KEY idx_sn_price_change_price (PRICE_ID, CREATE_TIME),
  KEY idx_sn_price_change_scope (SN_ID, DISTRIBUTOR_ID, CREATE_TIME)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='经销商SN特价变更记录';

DROP TABLE IF EXISTS T_PRODUCT_IMPORT_TASK;
CREATE TABLE T_PRODUCT_IMPORT_TASK (
  TASK_ID          VARCHAR(32) PRIMARY KEY COMMENT '导入任务ID',
  TASK_NO          VARCHAR(64) NOT NULL UNIQUE COMMENT '导入任务号',
  IMPORT_TYPE      VARCHAR(32) NOT NULL COMMENT '导入类型:product/price',
  SOURCE_FILE_NAME VARCHAR(255) COMMENT '来源文件名',
  FILE_DATA        LONGBLOB NOT NULL COMMENT '待处理Excel文件',
  TOTAL_ROWS       INT DEFAULT 0 COMMENT '文件总行数',
  PROCESSED_ROWS   INT DEFAULT 0 COMMENT '已处理行数',
  VALID_ROWS       INT DEFAULT 0 COMMENT '校验通过行数',
  SUCCESS_ROWS     INT DEFAULT 0 COMMENT '成功行数',
  FAILED_ROWS      INT DEFAULT 0 COMMENT '失败行数',
  AFFECTED_PRODUCTS INT DEFAULT 0 COMMENT '影响商品数',
  PRICE_CHANGES    INT DEFAULT 0 COMMENT '价格变更数',
  PENDING_CHANGES  INT DEFAULT 0 COMMENT '待生效价格变更数',
  EFFECTIVE_CHANGES INT DEFAULT 0 COMMENT '已生效价格变更数',
  BATCH_NO         VARCHAR(64) COMMENT '价格导入批次号',
  STATUS           VARCHAR(32) DEFAULT 'queued' COMMENT '状态:queued/processing/completed/partial_failed/failed',
  ERROR_JSON       LONGTEXT COMMENT '失败行快照',
  ERROR_MESSAGE    VARCHAR(1000) COMMENT '任务失败原因',
  CREATE_USER      VARCHAR(64) COMMENT '提交人',
  CREATE_TIME      TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  START_TIME       DATETIME COMMENT '开始处理时间',
  FINISH_TIME      DATETIME COMMENT '完成时间',
  KEY idx_product_import_task_status (STATUS, CREATE_TIME)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='商品及定价异步导入任务';

DROP TABLE IF EXISTS T_PRODUCT_PRICE_IMPORT_BATCH;
CREATE TABLE T_PRODUCT_PRICE_IMPORT_BATCH (
  BATCH_ID         VARCHAR(32) PRIMARY KEY COMMENT '批次ID',
  BATCH_NO         VARCHAR(64) NOT NULL UNIQUE COMMENT '批次号',
  SOURCE_FILE_NAME VARCHAR(255) COMMENT '来源文件名',
  TOTAL_ROWS       INT DEFAULT 0 COMMENT '导入行数',
  TOTAL_PRODUCTS   INT DEFAULT 0 COMMENT '影响商品数',
  TOTAL_CHANGES    INT DEFAULT 0 COMMENT '价格变更条数',
  STATUS           VARCHAR(32) DEFAULT 'effective' COMMENT '状态:effective/pending/failed',
  REMARK           VARCHAR(512) COMMENT '备注',
  CREATE_USER      VARCHAR(64) COMMENT '导入人',
  CREATE_TIME      TIMESTAMP DEFAULT CURRENT_TIMESTAMP COMMENT '导入时间',
  KEY idx_price_batch_status (STATUS)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='商品价格导入批次表';

DROP TABLE IF EXISTS T_PRODUCT_PRICE_CHANGE_LOG;
CREATE TABLE T_PRODUCT_PRICE_CHANGE_LOG (
  CHANGE_ID         VARCHAR(32) PRIMARY KEY COMMENT '变更ID',
  BATCH_ID          VARCHAR(32) COMMENT '批次ID',
  BATCH_NO          VARCHAR(64) COMMENT '批次号',
  ROW_NO            INT COMMENT 'Excel行号',
  PRODUCT_ID        VARCHAR(32) NOT NULL COMMENT '商品ID',
  PRODUCT_CODE      VARCHAR(32) COMMENT '商品编码',
  PRODUCT_NAME      VARCHAR(255) COMMENT '商品名称快照',
  MANUFACTURER_CODE VARCHAR(128) COMMENT '厂商编码',
  PRICE_FIELD       VARCHAR(32) NOT NULL COMMENT '价格字段:standard_price/min_sale_price',
  OLD_PRICE         DECIMAL(12,2) DEFAULT 0 COMMENT '调整前价格',
  NEW_PRICE         DECIMAL(12,2) NOT NULL COMMENT '调整后价格',
  EFFECTIVE_TIME    DATETIME NOT NULL COMMENT '生效时间',
  SOURCE            VARCHAR(32) DEFAULT 'import' COMMENT '来源:import/manual',
  CHANGE_REASON     VARCHAR(512) COMMENT '调价原因',
  REMARK            VARCHAR(512) COMMENT '备注',
  STATUS            VARCHAR(32) DEFAULT 'pending' COMMENT '状态:pending/effective/failed',
  CREATE_USER       VARCHAR(64) COMMENT '操作人',
  CREATE_TIME       TIMESTAMP DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  APPLIED_TIME      DATETIME COMMENT '实际生效时间',
  FAIL_REASON       VARCHAR(512) COMMENT '失败原因',
  KEY idx_price_change_product (PRODUCT_ID),
  KEY idx_price_change_batch (BATCH_ID),
  KEY idx_price_change_status_time (STATUS, EFFECTIVE_TIME)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='商品价格变更记录表';

-- -------------------------------------------
-- 四、库房管理
-- -------------------------------------------

-- T_LOCATION: 门店标准仓位表
DROP TABLE IF EXISTS T_LOCATION;
CREATE TABLE T_LOCATION (
  LOCATION_ID  VARCHAR(32) PRIMARY KEY COMMENT '仓位实例ID',
  STORE_ID     VARCHAR(32) NOT NULL COMMENT '所属门店',
  NAME         VARCHAR(64) NOT NULL COMMENT '仓位名称',
  TYPE         VARCHAR(32) DEFAULT 'normal_qty' COMMENT '仓位编码:normal_qty/demo_qty/display_qty/unsellable_qty/pending_qty',
  IS_SELLABLE  TINYINT(1) DEFAULT 1 COMMENT '是否允许销售',
  STATUS       TINYINT DEFAULT 1,
  CREATE_TIME  TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  UPDATE_TIME  TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  KEY idx_location_store (STORE_ID),
  KEY idx_location_store_type (STORE_ID, TYPE)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='门店标准仓位表';

-- T_INVENTORY_WARNING: 库存预警配置表
DROP TABLE IF EXISTS T_INVENTORY_WARNING;
CREATE TABLE T_INVENTORY_WARNING (
  WARNING_ID   VARCHAR(32) PRIMARY KEY,
  PRODUCT_ID   VARCHAR(32) COMMENT '商品ID(为空按类别)',
  CATEGORY     VARCHAR(64) COMMENT '商品类别',
  MIN_STOCK    INT DEFAULT 0 COMMENT '最低库存预警',
  AGING_DAYS   INT DEFAULT 90 COMMENT '库龄预警天数',
  WARNING_TYPE VARCHAR(32) COMMENT '类型:low_stock-库存不足,aging-库龄超期',
  STATUS       TINYINT DEFAULT 1,
  CREATE_TIME  TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  UPDATE_TIME  TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  KEY idx_product_warning (PRODUCT_ID),
  KEY idx_category_warning (CATEGORY)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='库存预警配置表';

-- -------------------------------------------
-- 五、采购管理
-- -------------------------------------------

-- T_SUPPLIER: 供应商表
DROP TABLE IF EXISTS T_SUPPLIER;
CREATE TABLE T_SUPPLIER (
  SUPPLIER_ID   VARCHAR(32) PRIMARY KEY,
  NAME          VARCHAR(255) NOT NULL COMMENT '供应商名称',
  CONTACT       VARCHAR(64) COMMENT '联系人',
  PHONE         VARCHAR(32) COMMENT '联系电话',
  ADDRESS       VARCHAR(512) COMMENT '地址',
  IS_SERVICE_PROVIDER TINYINT(1) DEFAULT 1 COMMENT '是否服务商',
  GROSS_PROFIT_UPLIFT_AMOUNT DECIMAL(12,2) DEFAULT 0 COMMENT '非服务商每件毛利上浮金额',
  SORT_ORDER    INT DEFAULT 0 COMMENT '排序',
  STATUS        TINYINT DEFAULT 1,
  CREATE_TIME   TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  UPDATE_TIME   TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  IS_DELETED    TINYINT(1) DEFAULT 0
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='供应商表';

-- T_PURCHASE_REQUEST: 采购申请表
DROP TABLE IF EXISTS T_PURCHASE_REQUEST;
CREATE TABLE T_PURCHASE_REQUEST (
  REQUEST_ID    VARCHAR(32) PRIMARY KEY COMMENT '申请单ID',
  REQUEST_NO   VARCHAR(64) NOT NULL UNIQUE COMMENT '申请单号',
  STORE_ID     VARCHAR(32) NOT NULL COMMENT '申请门店',
  SUPPLIER_ID  VARCHAR(32) COMMENT '供应商',
  TOTAL_AMOUNT DECIMAL(12,2) COMMENT '申请金额',
  REASON       TEXT COMMENT '申请原因',
  STATUS       VARCHAR(32) DEFAULT 'pending' COMMENT '状态:pending-待审批,approved-已审批,rejected-已拒绝,purchased-已采购',
  APPLY_USER   VARCHAR(64) COMMENT '申请人',
  APPROVE_USER VARCHAR(64) COMMENT '审批人',
  APPROVE_COMMENT VARCHAR(512) COMMENT '审批意见',
  CREATE_TIME  TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  UPDATE_TIME  TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  KEY idx_request_store (STORE_ID),
  KEY idx_request_status (STATUS)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='采购申请表';

-- T_PURCHASE_REQUEST_ITEM: 采购申请明细
DROP TABLE IF EXISTS T_PURCHASE_REQUEST_ITEM;
CREATE TABLE T_PURCHASE_REQUEST_ITEM (
  ITEM_ID      BIGINT(20) AUTO_INCREMENT PRIMARY KEY,
  REQUEST_ID   VARCHAR(32) NOT NULL COMMENT '关联申请单',
  PRODUCT_ID   VARCHAR(32) NOT NULL COMMENT '商品ID',
  PRODUCT_NAME VARCHAR(255) COMMENT '商品名称(快照)',
  PN_CODE     VARCHAR(64) COMMENT 'PN料号(快照)',
  QUANTITY    INT NOT NULL COMMENT '申请数量',
  UNIT_PRICE  DECIMAL(12,2) COMMENT '期望单价',
  SUBTOTAL    DECIMAL(12,2) COMMENT '小计',
  KEY idx_request_item (REQUEST_ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='采购申请明细表';

-- T_PURCHASE_ORDER: 采购单主表
DROP TABLE IF EXISTS T_PURCHASE_ORDER;
CREATE TABLE T_PURCHASE_ORDER (
  ORDER_ID     VARCHAR(32) PRIMARY KEY COMMENT '采购单ID',
  ORDER_NO    VARCHAR(64) NOT NULL UNIQUE COMMENT '采购单号',
  REQUEST_ID  VARCHAR(32) COMMENT '关联申请单',
  STORE_ID   VARCHAR(32) NOT NULL COMMENT '收货门店',
  SUPPLIER_ID VARCHAR(32) NOT NULL COMMENT '供应商',
  TOTAL_AMOUNT DECIMAL(12,2) COMMENT '采购总金额',
  TOTAL_QUANTITY INT COMMENT '采购总数量',
  STATUS     VARCHAR(32) DEFAULT 'purchased' COMMENT '状态:purchased-已采购,partial_inbound-部分入库,completed-已完成',
  CREATE_USER VARCHAR(64) COMMENT '制单人',
  CREATE_TIME TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  UPDATE_TIME TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  KEY idx_purchase_store (STORE_ID),
  KEY idx_purchase_supplier (SUPPLIER_ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='采购单主表';

-- T_PURCHASE_ORDER_ITEM: 采购单明细
DROP TABLE IF EXISTS T_PURCHASE_ORDER_ITEM;
CREATE TABLE T_PURCHASE_ORDER_ITEM (
  ITEM_ID      BIGINT(20) AUTO_INCREMENT PRIMARY KEY,
  ORDER_ID     VARCHAR(32) NOT NULL,
  PRODUCT_ID   VARCHAR(32) NOT NULL,
  PRODUCT_NAME VARCHAR(255) COMMENT '商品名称(快照)',
  PN_CODE     VARCHAR(64) COMMENT 'PN料号',
  QUANTITY    INT NOT NULL COMMENT '采购数量',
  UNIT_PRICE  DECIMAL(12,2) COMMENT '采购单价',
  SUBTOTAL    DECIMAL(12,2) COMMENT '小计',
  KEY idx_order_item (ORDER_ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='采购单明细表';

-- -------------------------------------------
-- 六、销售管理
-- -------------------------------------------

-- T_ORDER: 销售订单主表
DROP TABLE IF EXISTS T_ORDER;
CREATE TABLE T_ORDER (
  ORDER_ID        VARCHAR(32) PRIMARY KEY COMMENT '订单ID',
  ORDER_NO       VARCHAR(64) NOT NULL UNIQUE COMMENT '订单编号',
  STORE_ID       VARCHAR(32) NOT NULL COMMENT '销售门店',
  CREATE_USER   VARCHAR(64) COMMENT '制单人',
  CUSTOMER_NAME  VARCHAR(64) COMMENT '客户姓名',
  CUSTOMER_PHONE VARCHAR(32) COMMENT '客户电话',
  CUSTOMER_SOURCE VARCHAR(64) COMMENT '客户来源',
  TOTAL_AMOUNT   DECIMAL(12,2) NOT NULL DEFAULT 0 COMMENT '订单总金额',
  DISCOUNT_AMOUNT DECIMAL(12,2) DEFAULT 0 COMMENT '优惠金额',
  NATIONAL_SUBSIDY DECIMAL(12,2) DEFAULT 0 COMMENT '国补',
  EDUCATION_SUBSIDY DECIMAL(12,2) DEFAULT 0 COMMENT '教育补贴',
  DEPOSIT_DEDUCTION_TOTAL DECIMAL(12,2) DEFAULT 0 COMMENT '定金抵扣总额',
  DEPOSIT_ITEMS JSON COMMENT '定金抵扣明细快照',
  ACTUAL_PAYMENT DECIMAL(12,2) NOT NULL DEFAULT 0 COMMENT '实际收款',
  INVOICE_STATUS VARCHAR(32) DEFAULT '不开票' COMMENT '开票状态',
  ORDER_STATUS   VARCHAR(32) DEFAULT 'completed' COMMENT '订单状态',
  SUBSIDY_STATUS VARCHAR(32) COMMENT '补贴状态',
  SUBSIDY_PERSON VARCHAR(64) COMMENT '补贴人姓名',
  SUBSIDY_ID    VARCHAR(32) COMMENT '补贴人ID',
  REMARK         TEXT COMMENT '备注',
  CREATE_TIME    TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  UPDATE_TIME    TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  IS_DELETED     TINYINT(1) DEFAULT 0,
  KEY idx_order_store (STORE_ID),
  KEY idx_order_no (ORDER_NO),
  KEY idx_order_time (CREATE_TIME),
  KEY idx_order_bi_scope (IS_DELETED, ORDER_STATUS, STORE_ID, CREATE_TIME)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='销售订单主表';

-- T_ORDER_ITEM: 订单明细表
DROP TABLE IF EXISTS T_ORDER_ITEM;
CREATE TABLE T_ORDER_ITEM (
  ITEM_ID      BIGINT(20) AUTO_INCREMENT PRIMARY KEY,
  ORDER_ID     VARCHAR(32) NOT NULL,
  PRODUCT_ID   VARCHAR(32) NOT NULL COMMENT '商品ID',
  PRODUCT_NAME VARCHAR(255) COMMENT '商品名称(快照)',
  PN_CODE     VARCHAR(64) COMMENT 'PN料号(快照)',
  SN_ID       VARCHAR(32) COMMENT 'SN序列号ID',
  SN_CODE     VARCHAR(128) COMMENT 'SN序列号(快照)',
  IMEI1       VARCHAR(32) COMMENT 'IMEI1(快照)',
  IMEI2       VARCHAR(32) COMMENT 'IMEI2(快照)',
  SALE_PRICE  DECIMAL(12,2) NOT NULL COMMENT '销售单价',
  QUANTITY    INT NOT NULL DEFAULT 1 COMMENT '数量',
  SUBTOTAL    DECIMAL(12,2) NOT NULL COMMENT '小计',
  SUPPLIER_ID  VARCHAR(32) COMMENT '采购来源供应商ID快照',
  SUPPLIER_NAME VARCHAR(255) COMMENT '采购来源供应商名称快照',
  USE_GOV_SUBSIDY TINYINT(1) DEFAULT 0 COMMENT '本行使用国补权益',
  USE_EDU_SUBSIDY TINYINT(1) DEFAULT 0 COMMENT '本行使用教育补贴权益',
  USE_SALES_REPORT TINYINT(1) DEFAULT 0 COMMENT '本行使用销量报号权益',
  SELECTED_RESOURCE_TYPES TEXT COMMENT '动态选择的资源类别JSON',
  KEY idx_order_item (ORDER_ID),
  KEY idx_product_item (PRODUCT_ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='订单明细表';

-- T_ORDER_PAYMENT: 订单支付记录表
DROP TABLE IF EXISTS T_ORDER_PAYMENT;
CREATE TABLE T_ORDER_PAYMENT (
  PAYMENT_ID    BIGINT(20) AUTO_INCREMENT PRIMARY KEY,
  ORDER_ID     VARCHAR(32) NOT NULL COMMENT '订单ID',
  PAYMENT_METHOD VARCHAR(64) NOT NULL COMMENT '支付方式',
  DEPOSIT_ID   VARCHAR(32) COMMENT '定金单ID',
  AMOUNT       DECIMAL(12,2) NOT NULL COMMENT '支付金额',
  PAYMENT_TIME TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  KEY idx_order_payment (ORDER_ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='订单支付记录表';

-- T_ORDER_SUPPLEMENT: 订单金额补录（方向快照用于毛利计算）
DROP TABLE IF EXISTS T_ORDER_SUPPLEMENT;
CREATE TABLE T_ORDER_SUPPLEMENT (
  SUPPLEMENT_ID VARCHAR(32) PRIMARY KEY COMMENT '补录记录ID',
  ORDER_ID VARCHAR(32) NOT NULL COMMENT '订单ID',
  ITEM_ID VARCHAR(64) COMMENT '补录项目ID',
  ITEM_NAME VARCHAR(128) NOT NULL COMMENT '补录项目名称快照',
  AMOUNT DECIMAL(12,2) NOT NULL COMMENT '补录金额绝对值',
  AMOUNT_TYPE VARCHAR(16) NOT NULL DEFAULT 'increase' COMMENT 'increase/decrease',
  CONTENT VARCHAR(500) COMMENT '补录说明',
  PROOF_PHOTO_URL VARCHAR(1024) COMMENT '凭证地址',
  CREATE_STAFF_ID BIGINT(20) COMMENT '录入人ID',
  CREATE_USER VARCHAR(64) COMMENT '录入人',
  CREATE_TIME DATETIME DEFAULT CURRENT_TIMESTAMP,
  UPDATE_TIME DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  IS_DELETED TINYINT(1) DEFAULT 0,
  KEY idx_order_supplement (ORDER_ID, IS_DELETED)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='订单金额补录记录';

-- T_ORDER_GROSS_PROFIT: 订单经营毛利计算快照
DROP TABLE IF EXISTS T_ORDER_GROSS_PROFIT;
CREATE TABLE T_ORDER_GROSS_PROFIT (
  GROSS_PROFIT_ID VARCHAR(32) PRIMARY KEY COMMENT '毛利快照ID',
  ORDER_ID VARCHAR(32) NOT NULL COMMENT '订单ID',
  ORDER_NO VARCHAR(64) NOT NULL COMMENT '订单号快照',
  STORE_ID VARCHAR(32) NOT NULL COMMENT '门店ID快照',
  FORMULA_VERSION VARCHAR(32) NOT NULL COMMENT '公式版本',
  RECEIVED_AMOUNT DECIMAL(12,2) NOT NULL DEFAULT 0 COMMENT '兼容旧版用户实收字段',
  RECEIVABLE_AMOUNT DECIMAL(12,2) NOT NULL DEFAULT 0 COMMENT '用户应收',
  SETTLEMENT_COST_AMOUNT DECIMAL(12,2) NOT NULL DEFAULT 0 COMMENT '兼容旧版销售结算成本',
  PRODUCT_PRICING_AMOUNT DECIMAL(12,2) NOT NULL DEFAULT 0 COMMENT '订单产品定价合计',
  PAYMENT_FEE_AMOUNT DECIMAL(12,2) NOT NULL DEFAULT 0 COMMENT '收款方式税率费用',
  INVOICE_AMOUNT DECIMAL(12,2) NOT NULL DEFAULT 0 COMMENT '开票金额',
  VAT_TAXABLE_AMOUNT DECIMAL(12,2) NOT NULL DEFAULT 0 COMMENT '增值税计税差额',
  VAT_AMOUNT DECIMAL(12,2) NOT NULL DEFAULT 0 COMMENT '增值税',
  SUPPLEMENT_AMOUNT DECIMAL(12,2) NOT NULL DEFAULT 0 COMMENT '补录净额',
  GROSS_PROFIT_AMOUNT DECIMAL(12,2) NOT NULL DEFAULT 0 COMMENT '经营毛利',
  PAYMENT_FEE_DETAILS JSON COMMENT '收款税率计算明细',
  SETTLEMENT_COST_DETAILS JSON COMMENT '兼容旧版商品结算成本明细',
  PRODUCT_PRICING_DETAILS JSON COMMENT '订单产品定价明细',
  SUPPLEMENT_DETAILS JSON COMMENT '补录计算明细',
  SNAPSHOT_STATUS VARCHAR(16) NOT NULL DEFAULT 'draft' COMMENT 'draft/final',
  CALCULATED_BY VARCHAR(64) COMMENT '计算人',
  CALCULATED_AT DATETIME DEFAULT CURRENT_TIMESTAMP,
  CREATE_TIME DATETIME DEFAULT CURRENT_TIMESTAMP,
  UPDATE_TIME DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  UNIQUE KEY uk_order_gross_profit (ORDER_ID),
  KEY idx_gross_profit_analysis (STORE_ID, SNAPSHOT_STATUS, CALCULATED_AT)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='订单经营毛利计算快照';

-- T_DEPOSIT_ORDER: 定金单
DROP TABLE IF EXISTS T_DEPOSIT_ORDER;
CREATE TABLE T_DEPOSIT_ORDER (
  DEPOSIT_ID VARCHAR(32) PRIMARY KEY COMMENT '定金单ID',
  DEPOSIT_NO VARCHAR(64) NOT NULL UNIQUE COMMENT '定金单号',
  STORE_ID VARCHAR(32) NOT NULL COMMENT '门店ID',
  CUSTOMER_NAME VARCHAR(64) COMMENT '客户姓名',
  CUSTOMER_PHONE VARCHAR(32) COMMENT '客户电话',
  CUSTOMER_SOURCE VARCHAR(64) COMMENT '客户来源',
  AMOUNT DECIMAL(12,2) NOT NULL DEFAULT 0 COMMENT '定金金额',
  REDEEMED_AMOUNT DECIMAL(12,2) NOT NULL DEFAULT 0 COMMENT '已核销金额',
  REFUNDED_AMOUNT DECIMAL(12,2) NOT NULL DEFAULT 0 COMMENT '已退款金额',
  STATUS VARCHAR(32) DEFAULT 'available' COMMENT '状态:available/redeemed/refunded/voided',
  RELATED_ORDER_ID VARCHAR(32) COMMENT '核销销售订单ID',
  RELATED_ORDER_NO VARCHAR(64) COMMENT '核销销售订单号',
  REMARK TEXT COMMENT '备注',
  CREATE_STAFF_ID BIGINT(20) COMMENT '收取定金店员ID',
  CREATE_USER VARCHAR(64) COMMENT '收取定金店员',
  CREATE_TIME TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  ARCHIVE_USER VARCHAR(64) COMMENT '归档人',
  ARCHIVE_TIME DATETIME COMMENT '归档时间',
  UPDATE_TIME TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  IS_DELETED TINYINT(1) DEFAULT 0,
  KEY idx_deposit_store (STORE_ID),
  KEY idx_deposit_staff_status (CREATE_STAFF_ID, STATUS),
  KEY idx_deposit_customer (CUSTOMER_PHONE)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='定金单';

-- T_DEPOSIT_REFUND: 定金退款记录
DROP TABLE IF EXISTS T_DEPOSIT_REFUND;
CREATE TABLE T_DEPOSIT_REFUND (
  REFUND_ID VARCHAR(32) PRIMARY KEY COMMENT '退款记录ID',
  REFUND_NO VARCHAR(64) NOT NULL UNIQUE COMMENT '退款记录号',
  DEPOSIT_ID VARCHAR(32) NOT NULL COMMENT '定金单ID',
  AMOUNT DECIMAL(12,2) NOT NULL COMMENT '退款金额',
  REASON VARCHAR(512) COMMENT '退款原因',
  CREATE_STAFF_ID BIGINT(20) COMMENT '记录人ID',
  CREATE_USER VARCHAR(64) COMMENT '记录人',
  CREATE_TIME TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  KEY idx_deposit_refund_deposit (DEPOSIT_ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='定金退款记录';

-- T_DEPOSIT_REDEMPTION: 定金核销记录
DROP TABLE IF EXISTS T_DEPOSIT_REDEMPTION;
CREATE TABLE T_DEPOSIT_REDEMPTION (
  REDEMPTION_ID VARCHAR(32) PRIMARY KEY COMMENT '核销记录ID',
  DEPOSIT_ID VARCHAR(32) NOT NULL COMMENT '定金单ID',
  ORDER_ID VARCHAR(32) NOT NULL COMMENT '销售订单ID',
  ORDER_NO VARCHAR(64) COMMENT '销售订单号',
  AMOUNT DECIMAL(12,2) NOT NULL COMMENT '核销金额',
  STATUS VARCHAR(32) DEFAULT 'active' COMMENT '状态:active/voided',
  VOID_REASON VARCHAR(512) COMMENT '作废原因',
  VOID_TIME DATETIME COMMENT '作废时间',
  CREATE_STAFF_ID BIGINT(20) COMMENT '核销人ID',
  CREATE_USER VARCHAR(64) COMMENT '核销人',
  CREATE_TIME TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  KEY idx_deposit_redemption_deposit (DEPOSIT_ID),
  KEY idx_deposit_redemption_order (ORDER_ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='定金核销记录';

-- T_ORDER_ATTACHMENT: 订单附件表
DROP TABLE IF EXISTS T_ORDER_ATTACHMENT;
CREATE TABLE T_ORDER_ATTACHMENT (
  ATTACH_ID   BIGINT(20) AUTO_INCREMENT PRIMARY KEY,
  ORDER_ID   VARCHAR(32) NOT NULL,
  ATTACH_TYPE VARCHAR(64) COMMENT '附件类型:subsidy_photo-补贴照片,product_photo-商品照片',
  FILE_URL   VARCHAR(1024) NOT NULL COMMENT '文件URL',
  CREATE_TIME TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  KEY idx_attach_order (ORDER_ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='订单附件表';

-- T_PERFORMANCE_PROFIT_ADJUSTMENT: 员工业绩毛利调整申请
DROP TABLE IF EXISTS T_PERFORMANCE_PROFIT_ADJUSTMENT_ATTACHMENT;
DROP TABLE IF EXISTS T_PERFORMANCE_PROFIT_ADJUSTMENT;
CREATE TABLE T_PERFORMANCE_PROFIT_ADJUSTMENT (
  ADJUSTMENT_ID VARCHAR(32) PRIMARY KEY,
  ADJUSTMENT_NO VARCHAR(64) NOT NULL UNIQUE,
  ORDER_ID VARCHAR(32) NOT NULL,
  ORDER_NO VARCHAR(64) NOT NULL,
  STORE_ID VARCHAR(32) NOT NULL,
  EMPLOYEE_NAME VARCHAR(64),
  ADJUSTMENT_TYPE VARCHAR(16) NOT NULL COMMENT '类型:increase/decrease',
  AMOUNT DECIMAL(12,2) NOT NULL,
  SIGNED_AMOUNT DECIMAL(12,2) NOT NULL,
  BASE_GROSS_PROFIT DECIMAL(12,2) DEFAULT 0,
  REASON VARCHAR(1000) NOT NULL,
  STATUS VARCHAR(32) DEFAULT 'pending_finance' COMMENT '状态:pending_finance/pending_admin/approved/rejected',
  APPLICANT_STAFF_ID BIGINT(20) NOT NULL,
  APPLICANT_NAME VARCHAR(64) NOT NULL,
  FINANCE_REVIEWER_ID BIGINT(20),
  FINANCE_REVIEWER_NAME VARCHAR(64),
  FINANCE_REVIEW_COMMENT VARCHAR(512),
  FINANCE_REVIEW_TIME DATETIME,
  ADMIN_REVIEWER_ID BIGINT(20),
  ADMIN_REVIEWER_NAME VARCHAR(64),
  ADMIN_REVIEW_COMMENT VARCHAR(512),
  ADMIN_REVIEW_TIME DATETIME,
  REJECT_STAGE VARCHAR(32),
  CREATE_TIME TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  UPDATE_TIME TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  KEY idx_ppa_order_status (ORDER_ID, STATUS),
  KEY idx_ppa_applicant (APPLICANT_STAFF_ID, CREATE_TIME),
  KEY idx_ppa_status_time (STATUS, CREATE_TIME)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='员工业绩毛利调整申请表';

CREATE TABLE T_PERFORMANCE_PROFIT_ADJUSTMENT_ATTACHMENT (
  ATTACHMENT_ID VARCHAR(32) PRIMARY KEY,
  ADJUSTMENT_ID VARCHAR(32) NOT NULL,
  ORIGINAL_NAME VARCHAR(255) NOT NULL,
  STORAGE_NAME VARCHAR(255) NOT NULL,
  MIME_TYPE VARCHAR(128),
  FILE_SIZE BIGINT(20) DEFAULT 0,
  FILE_PATH VARCHAR(1024) NOT NULL,
  UPLOAD_STAFF_ID BIGINT(20) NOT NULL,
  UPLOAD_USER VARCHAR(64),
  CREATE_TIME TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  KEY idx_ppaa_adjustment (ADJUSTMENT_ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='员工业绩毛利调整附件表';

-- -------------------------------------------
-- 七、库房操作
-- -------------------------------------------

-- T_INBOUND: 入库单主表
DROP TABLE IF EXISTS T_INBOUND;
CREATE TABLE T_INBOUND (
  INBOUND_ID   VARCHAR(32) PRIMARY KEY COMMENT '入库单ID',
  INBOUND_NO  VARCHAR(64) NOT NULL UNIQUE COMMENT '入库单号',
  STORE_ID    VARCHAR(32) NOT NULL COMMENT '收货门店',
  SOURCE_TYPE VARCHAR(32) COMMENT '来源类型:purchase-采购入库,return-退货入库,transfer-调拨入库',
  SOURCE_NO   VARCHAR(64) COMMENT '来源单号',
  TOTAL_AMOUNT DECIMAL(12,2) COMMENT '入库总金额',
  TOTAL_QUANTITY INT COMMENT '入库总数量',
  STATUS      VARCHAR(32) DEFAULT 'pending' COMMENT '状态:pending-待入库,partial-部分入库,completed-已完成',
  CREATE_USER VARCHAR(64) COMMENT '制单人',
  CREATE_TIME TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  UPDATE_TIME TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  KEY idx_inbound_store (STORE_ID),
  KEY idx_inbound_no (INBOUND_NO)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='入库单主表';

-- T_INBOUND_ITEM: 入库明细表
DROP TABLE IF EXISTS T_INBOUND_ITEM;
CREATE TABLE T_INBOUND_ITEM (
  ITEM_ID     BIGINT(20) AUTO_INCREMENT PRIMARY KEY,
  INBOUND_ID  VARCHAR(32) NOT NULL,
  PRODUCT_ID  VARCHAR(32) NOT NULL,
  PRODUCT_NAME VARCHAR(255) COMMENT '商品名称(快照)',
  PN_CODE    VARCHAR(64) COMMENT 'PN料号',
  SN_ID      VARCHAR(32) COMMENT 'SN ID(入库后生成)',
  SN_CODE    VARCHAR(128) COMMENT 'SN序列号',
  UNIT_PRICE DECIMAL(12,2) COMMENT '入库单价',
  QUANTITY   INT NOT NULL DEFAULT 1 COMMENT '数量',
  KEY idx_inbound_item (INBOUND_ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='入库明细表';

-- T_OUTBOUND: 出库单主表
DROP TABLE IF EXISTS T_OUTBOUND;
CREATE TABLE T_OUTBOUND (
  OUTBOUND_ID  VARCHAR(32) PRIMARY KEY COMMENT '出库单ID',
  OUTBOUND_NO VARCHAR(64) NOT NULL UNIQUE COMMENT '出库单号',
  STORE_ID   VARCHAR(32) NOT NULL COMMENT '出库门店',
  DEST_STORE_ID VARCHAR(32) COMMENT '目标门店(调拨时)',
  OUT_TYPE  VARCHAR(32) COMMENT '出库类型:sale-销售出库,return-退货出库,transfer-调拨出库,loss-报损',
  SOURCE_ORDER_NO VARCHAR(64) COMMENT '来源单号',
  TOTAL_QUANTITY INT COMMENT '出库总数量',
  STATUS     VARCHAR(32) DEFAULT 'pending' COMMENT '状态:pending-待出库,completed-已完成',
  CREATE_USER VARCHAR(64) COMMENT '制单人',
  CREATE_TIME TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  UPDATE_TIME TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  KEY idx_outbound_store (STORE_ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='出库单主表';

-- T_OUTBOUND_ITEM: 出库明细表
DROP TABLE IF EXISTS T_OUTBOUND_ITEM;
CREATE TABLE T_OUTBOUND_ITEM (
  ITEM_ID     BIGINT(20) AUTO_INCREMENT PRIMARY KEY,
  OUTBOUND_ID VARCHAR(32) NOT NULL,
  PRODUCT_ID  VARCHAR(32) NOT NULL,
  SN_ID      VARCHAR(32) COMMENT 'SN ID',
  SN_CODE    VARCHAR(128) COMMENT 'SN序列号',
  QUANTITY   INT NOT NULL DEFAULT 1,
  KEY idx_outbound_item (OUTBOUND_ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='出库明细表';

-- T_TRANSFER: 调拨单主表
DROP TABLE IF EXISTS T_TRANSFER;
CREATE TABLE T_TRANSFER (
  TRANSFER_ID  VARCHAR(32) PRIMARY KEY COMMENT '调拨单ID',
  TRANSFER_NO VARCHAR(64) NOT NULL UNIQUE COMMENT '调拨单号',
  FROM_STORE_ID VARCHAR(32) NOT NULL COMMENT '调出门店',
  TO_STORE_ID   VARCHAR(32) NOT NULL COMMENT '调入门店',
  TOTAL_QUANTITY INT COMMENT '调拨总数量',
  STATUS     VARCHAR(32) DEFAULT 'pending' COMMENT '状态:pending-待发货,shipping-发货中,received-已收货,completed-已完成',
  APPLY_USER  VARCHAR(64) COMMENT '申请人',
  CONFIRM_USER VARCHAR(64) COMMENT '确认人',
  CREATE_TIME TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  UPDATE_TIME TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  KEY idx_transfer_from (FROM_STORE_ID),
  KEY idx_transfer_to (TO_STORE_ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='调拨单主表';

-- T_TRANSFER_ITEM: 调拨明细表
DROP TABLE IF EXISTS T_TRANSFER_ITEM;
CREATE TABLE T_TRANSFER_ITEM (
  ITEM_ID     BIGINT(20) AUTO_INCREMENT PRIMARY KEY,
  TRANSFER_ID VARCHAR(32) NOT NULL,
  PRODUCT_ID  VARCHAR(32) NOT NULL,
  SN_ID      VARCHAR(32) COMMENT 'SN ID',
  SN_CODE    VARCHAR(128) COMMENT 'SN序列号',
  QUANTITY   INT NOT NULL DEFAULT 1,
  KEY idx_transfer_item (TRANSFER_ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='调拨明细表';

-- T_INVENTORY_CONVERSION: 库存拆分/组装转换单
DROP TABLE IF EXISTS T_INVENTORY_CONVERSION;
CREATE TABLE T_INVENTORY_CONVERSION (
  CONVERSION_ID VARCHAR(32) PRIMARY KEY COMMENT '库存转换单ID',
  CONVERSION_NO VARCHAR(64) NOT NULL UNIQUE COMMENT '库存转换单号',
  CONVERSION_TYPE VARCHAR(32) NOT NULL COMMENT '转换类型:split-拆分,assemble-组装',
  STORE_ID VARCHAR(32) NOT NULL COMMENT '门店ID',
  STATUS VARCHAR(32) DEFAULT 'completed' COMMENT '状态:completed-已完成,voided-已冲销',
  TOTAL_SOURCE_COST DECIMAL(12,2) DEFAULT 0 COMMENT '来源总成本',
  TOTAL_TARGET_COST DECIMAL(12,2) DEFAULT 0 COMMENT '目标总成本',
  SERVICE_COST DECIMAL(12,2) DEFAULT 0 COMMENT '组装服务成本',
  REMARK VARCHAR(512) COMMENT '备注',
  VOID_REASON VARCHAR(512) COMMENT '冲销原因',
  CREATE_USER VARCHAR(64) COMMENT '创建人',
  CREATE_TIME TIMESTAMP DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  VOID_USER VARCHAR(64) COMMENT '冲销人',
  VOID_TIME DATETIME COMMENT '冲销时间',
  KEY idx_inventory_conversion_store (STORE_ID),
  KEY idx_inventory_conversion_type_status (CONVERSION_TYPE, STATUS)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='库存拆分组装转换单';

-- T_INVENTORY_CONVERSION_ITEM: 库存拆分/组装转换明细
DROP TABLE IF EXISTS T_INVENTORY_CONVERSION_ITEM;
CREATE TABLE T_INVENTORY_CONVERSION_ITEM (
  ITEM_ID BIGINT(20) AUTO_INCREMENT PRIMARY KEY COMMENT '明细ID',
  CONVERSION_ID VARCHAR(32) NOT NULL COMMENT '转换单ID',
  LINE_ROLE VARCHAR(32) NOT NULL COMMENT '行角色:source-来源,target-目标,service-服务成本',
  PRODUCT_ID VARCHAR(32) COMMENT '商品ID',
  PRODUCT_NAME VARCHAR(255) COMMENT '商品名称快照',
  PN_CODE VARCHAR(64) COMMENT 'PN快照',
  SN_ID VARCHAR(32) COMMENT 'SN ID',
  SN_CODE VARCHAR(128) COMMENT 'SN快照',
  SOURCE_SN_ID VARCHAR(32) COMMENT '来源SN ID',
  SOURCE_SN_CODE VARCHAR(128) COMMENT '来源SN快照',
  QUANTITY INT DEFAULT 1 COMMENT '数量',
  UNIT_COST DECIMAL(12,2) DEFAULT 0 COMMENT '单位成本',
  TOTAL_COST DECIMAL(12,2) DEFAULT 0 COMMENT '总成本',
  INVENTORY_TYPE VARCHAR(32) DEFAULT 'normal_qty' COMMENT '库存类型',
  LOCATION_ID VARCHAR(32) COMMENT '库位ID',
  REMARK VARCHAR(512) COMMENT '备注',
  KEY idx_conversion_item_conversion (CONVERSION_ID),
  KEY idx_conversion_item_product (PRODUCT_ID),
  KEY idx_conversion_item_sn (SN_ID),
  KEY idx_conversion_item_source_sn (SOURCE_SN_ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='库存拆分组装转换明细';

-- -------------------------------------------
-- 八、财务管理
-- -------------------------------------------

-- T_DAILY_STATEMENT: 门店日结表
DROP TABLE IF EXISTS T_DAILY_STATEMENT;
CREATE TABLE T_DAILY_STATEMENT (
  STATEMENT_ID VARCHAR(32) PRIMARY KEY COMMENT '日结单ID',
  STORE_ID    VARCHAR(32) NOT NULL COMMENT '门店ID',
  STATEMENT_DATE DATE NOT NULL COMMENT '日结日期',
  TOTAL_REVENUE DECIMAL(12,2) DEFAULT 0 COMMENT '当日总收入',
  TOTAL_ORDER_COUNT INT DEFAULT 0 COMMENT '当日订单数',
  CASH_AMOUNT  DECIMAL(12,2) DEFAULT 0 COMMENT '现金收款',
  WECHAT_AMOUNT DECIMAL(12,2) DEFAULT 0 COMMENT '微信收款',
  ALIPAY_AMOUNT DECIMAL(12,2) DEFAULT 0 COMMENT '支付宝收款',
  OTHER_AMOUNT DECIMAL(12,2) DEFAULT 0 COMMENT '其他收款',
  DIFFERENCE   DECIMAL(12,2) DEFAULT 0 COMMENT '差异',
  STATUS      VARCHAR(32) DEFAULT 'draft' COMMENT '状态:draft-草稿,submitted-已提交,confirmed-已确认',
  SUBMIT_STAFF VARCHAR(64) COMMENT '提交人',
  CONFIRM_STAFF VARCHAR(64) COMMENT '确认人',
  CREATE_TIME TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  UPDATE_TIME TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  UNIQUE KEY uni_store_date (STORE_ID, STATEMENT_DATE)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='门店日结表';

-- T_EXPENSE: 支出记录表
DROP TABLE IF EXISTS T_EXPENSE;
CREATE TABLE T_EXPENSE (
  EXPENSE_ID  VARCHAR(32) PRIMARY KEY COMMENT '支出ID',
  EXPENSE_NO VARCHAR(64) NOT NULL UNIQUE COMMENT '支出编号',
  STORE_ID   VARCHAR(32) NOT NULL COMMENT '门店ID',
  EXPENSE_TYPE VARCHAR(32) NOT NULL COMMENT '支出类型:purchase-采购付款,operating-运营费用,other-其他',
  AMOUNT     DECIMAL(12,2) NOT NULL COMMENT '支出金额',
  PAYMENT_METHOD VARCHAR(64) COMMENT '支付方式',
  RELATED_ORDER_NO VARCHAR(64) COMMENT '关联单号',
  REMARK     VARCHAR(512) COMMENT '备注',
  CREATE_USER VARCHAR(64) COMMENT '制单人',
  CREATE_TIME TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  UPDATE_TIME TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  IS_DELETED  TINYINT(1) DEFAULT 0,
  KEY idx_expense_store (STORE_ID),
  KEY idx_expense_type (EXPENSE_TYPE)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='支出记录表';

-- -------------------------------------------
-- 九、字典表
-- -------------------------------------------

-- T_DICT_CUSTOMER_SOURCE: 客户来源字典
DROP TABLE IF EXISTS T_DICT_CUSTOMER_SOURCE;
CREATE TABLE T_DICT_CUSTOMER_SOURCE (
  SOURCE_ID   VARCHAR(64) PRIMARY KEY,
  PARENT_ID  VARCHAR(64) COMMENT '父级ID',
  NAME       VARCHAR(128) NOT NULL COMMENT '来源名称',
  LEVEL      INT DEFAULT 1 COMMENT '层级',
  SORT_ORDER INT DEFAULT 0,
  STATUS     TINYINT DEFAULT 1,
  CREATE_TIME TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  UPDATE_TIME TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='客户来源字典';

-- T_DICT_PAYMENT_METHOD: 支付方式字典
DROP TABLE IF EXISTS T_DICT_PAYMENT_METHOD;
CREATE TABLE T_DICT_PAYMENT_METHOD (
  METHOD_ID  VARCHAR(64) PRIMARY KEY,
  NAME      VARCHAR(128) NOT NULL COMMENT '支付方式名称',
  CODE      VARCHAR(64) NOT NULL UNIQUE COMMENT '支付方式代码',
  ICON      VARCHAR(64) COMMENT '图标',
  DEFAULT_TAX_RATE DECIMAL(8,4) NOT NULL DEFAULT 0 COMMENT '默认收款手续费税率（百分数）',
  SORT_ORDER INT DEFAULT 0,
  STATUS    TINYINT DEFAULT 1,
  CREATE_TIME TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  UPDATE_TIME TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='支付方式字典';

-- T_DICT_SUPPLEMENT_ITEM: 附加服务费字典
DROP TABLE IF EXISTS T_DICT_SUPPLEMENT_ITEM;
CREATE TABLE T_DICT_SUPPLEMENT_ITEM (
  ITEM_ID    VARCHAR(64) PRIMARY KEY,
  NAME      VARCHAR(128) NOT NULL COMMENT '项目名称',
  AMOUNT    DECIMAL(10,2) DEFAULT 0 COMMENT '默认金额',
  AMOUNT_TYPE VARCHAR(16) NOT NULL DEFAULT 'increase' COMMENT 'increase/decrease',
  IS_ACTIVE TINYINT(1) DEFAULT 1,
  SORT_ORDER INT DEFAULT 0,
  CREATE_TIME TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  UPDATE_TIME TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='附加服务费字典';

-- -------------------------------------------
-- 十、初始化数据
-- -------------------------------------------

-- 插入区域
INSERT INTO T_REGION (REGION_ID, REGION_CODE, NAME, SORT_ORDER) VALUES
('R001', 'CD', '成都区域', 1),
('R002', 'CQ', '重庆区域', 2),
('R003', 'DS', '地市区域', 3);

-- 插入角色
INSERT INTO T_ROLE (ROLE_ID, ROLE_CODE, NAME, DESCRIPTION, IS_SYSTEM) VALUES
('RL001', 'boss', '老板', '超级管理员，可查看所有数据', 1),
('RL002', 'finance', '财务', '财务管理人员', 1),
('RL003', 'purchase', '采购', '采购管理人员', 1),
('RL004', 'store_manager', '店长', '门店管理者', 1),
('RL005', 'staff', '店员', '普通店员', 1);

-- 插入支付方式
INSERT INTO T_DICT_PAYMENT_METHOD (METHOD_ID, NAME, CODE, ICON, SORT_ORDER) VALUES
('PM001', '微信支付', 'wechat', 'wechat-icon', 1),
('PM002', '支付宝', 'alipay', 'alipay-icon', 2),
('PM003', '现金', 'cash', 'cash-icon', 3),
('PM004', '银行卡', 'bankcard', 'bankcard-icon', 4),
('PM005', '其他', 'other', 'other-icon', 5),
('PM_DEPOSIT', '定金', 'deposit', 'deposit-icon', 99);

-- 插入菜单（权限模块）
INSERT INTO T_MENU (MENU_ID, MENU_CODE, NAME, PARENT_ID, MENU_TYPE, PATH, SORT_ORDER) VALUES
-- 一级菜单
('M001', 'home', '首页', NULL, 'menu', '/', 1),
('M002', 'sales', '销售管理', NULL, 'module', '/sales', 2),
('M003', 'inventory', '库存管理', NULL, 'module', '/inventory', 3),
('M004', 'purchase', '采购管理', NULL, 'module', '/purchase', 4),
('M005', 'finance', '财务管理', NULL, 'module', '/finance', 5),
('M006', 'products', '商品管理', NULL, 'module', '/products', 6),
('M007', 'stores', '门店管理', NULL, 'module', '/stores', 7),
('M008', 'system', '系统设置', NULL, 'module', '/system', 8),
('M009', 'reports', '报表统计', NULL, 'menu', '/reports', 9),
('M010', 'approval', '审批中心', NULL, 'menu', '/approval', 10),
-- 销售管理子菜单
('M201', 'sales_order', '销售订单', 'M002', 'menu', '/sales/order', 1),
('M204', 'sales_subsidy_photos', '国补照片', 'M002', 'menu', '/sales/subsidy-photos', 2),
-- 库房管理子菜单
('M301', 'inventory_summary', '库存汇总', 'M003', 'menu', '/inventory/summary', 1),
('M302', 'inventory_sn_inventory', 'SN库存清单', 'M003', 'menu', '/inventory/sn-inventory', 2),
('M303', 'inventory_batch_maintenance', '批量维护', 'M003', 'menu', '/inventory/batch-maintenance', 3),
('M304', 'inventory_inbound', '入库单管理', 'M003', 'menu', '/inventory/inbound', 4),
('M305', 'inventory_sn_trace', 'SN追踪', 'M003', 'menu', '/inventory/sn-trace', 5),
('M306', 'inventory_resource_rights', '库存资源权益', 'M003', 'menu', '/inventory/resource-rights', 6),
('M307', 'inventory_transfer', '调拨管理', 'M003', 'menu', '/inventory/transfer', 7),
('M308', 'inventory_conversion', '拆装管理', 'M003', 'menu', '/inventory/conversion', 8),
-- 采购管理子菜单
('M401', 'purchase_request', '采购申请', 'M004', 'menu', '/purchase/request', 1),
('M404', 'purchase_supplier', '供应商管理', 'M004', 'menu', '/purchase/supplier', 2),
-- 财务管理子菜单
('M501', 'finance_daily', '日结单', 'M005', 'menu', '/finance/daily', 1),
('M502', 'finance_subsidy_receivable', '国补应收单', 'M005', 'menu', '/finance/subsidy-receivable', 2),
('M503', 'finance_rebate_settlement', '返利下账', 'M005', 'menu', '/finance/rebate-settlement', 3),
('M504', 'finance_expense', '费用管理', 'M005', 'menu', '/finance/expense', 4),
('M505', 'finance_payable', '应付管理', 'M005', 'menu', '/finance/payable', 5),
('M506', 'finance_reimbursement', '报销结算', 'M005', 'menu', '/finance/reimbursement', 6),
('M507', 'finance_payment', '付款管理', 'M005', 'menu', '/finance/payment', 7),
('M508', 'finance_rebate', '返利管理', 'M005', 'menu', '/finance/rebate', 8),
('M509', 'finance_resource_rights', '资源权益核销与成本调整', 'M005', 'menu', '/finance/resource-rights', 9),
('M510', 'finance_account', '账户中心', 'M005', 'menu', '/finance/account', 10),
('M511', 'finance_settlement', '应付结算单管理', 'M005', 'menu', '/finance/settlement', 11),
-- 商品管理子菜单
('M601', 'product_product', '商品管理', 'M006', 'menu', '/products/product', 1),
('M602', 'product_category', '分类管理', 'M006', 'menu', '/products/category', 2),
('M604', 'product_price', '价格管理', 'M006', 'menu', '/products/price', 3),
('M605', 'product_approval', '新建商品审批', 'M006', 'menu', '/products/approval', 4),
-- 报表统计子菜单
('M901', 'reports_dashboard', '经营数据看板', 'M009', 'menu', '/reports/dashboard', 1),
('M902', 'reports_sales', '销售报表', 'M009', 'menu', '/reports/sales', 2),
('M903', 'reports_inventory', '库存报表', 'M009', 'menu', '/reports/inventory', 3),
('M904', 'reports_employee', '员工业绩统计', 'M009', 'menu', '/reports/employee', 4),
-- 审批中心子菜单
('M1001', 'approval_tasks', '待我审批', 'M010', 'menu', '/approval/tasks', 1),
('M1002', 'approval_instances', '我的申请', 'M010', 'menu', '/approval/instances', 2),
('M1003', 'approval_flows', '流程配置', 'M010', 'menu', '/approval/flows', 3),
-- 系统管理子菜单
('M801', 'system_users', '用户管理', 'M008', 'menu', '/system/users', 1),
('M802', 'system_roles', '角色管理', 'M008', 'menu', '/system/roles', 2),
('M803', 'system_menus', '菜单管理', 'M008', 'menu', '/system/menus', 3),
('M804', 'system_locations', '库位管理', 'M008', 'menu', '/system/locations', 4),
('M805', 'system_resource_categories', '货型配置', 'M008', 'menu', '/system/resource-categories', 5),
('M806', 'system_customer_source', '客户来源管理', 'M008', 'menu', '/system/customer-source', 6),
('M807', 'system_payment_method', '收款方式管理', 'M008', 'menu', '/system/payment-method', 7),
('M808', 'system_supplement_item', '金额补录项目管理', 'M008', 'menu', '/system/supplement-item', 8),
('M809', 'system_expense_type', '报销类型管理', 'M008', 'menu', '/system/expense-type', 9),
('M810', 'system_category_field', '商品字段管理', 'M008', 'menu', '/system/category-field', 10);

-- 给老板角色分配所有菜单
INSERT INTO T_ROLE_MENU (ROLE_ID, MENU_ID)
SELECT 'RL001', MENU_ID FROM T_MENU WHERE STATUS = 1;

-- 给财务角色分配财务和销售相关菜单
INSERT INTO T_ROLE_MENU (ROLE_ID, MENU_ID)
SELECT 'RL002', MENU_ID FROM T_MENU WHERE MENU_CODE IN (
  'home', 'sales', 'inventory', 'finance', 'reports', 'approval', 'products',
  'sales_order', 'sales_subsidy_photos',
  'inventory_resource_rights',
  'finance_daily', 'finance_subsidy_receivable', 'finance_rebate_settlement', 'finance_expense',
  'finance_payable', 'finance_reimbursement', 'finance_payment', 'finance_rebate',
  'finance_resource_rights', 'finance_account', 'finance_settlement',
  'reports_dashboard', 'reports_sales', 'reports_inventory', 'reports_employee',
  'approval_tasks', 'approval_instances', 'product_approval'
);

-- 给采购角色分配采购和库存菜单
INSERT INTO T_ROLE_MENU (ROLE_ID, MENU_ID)
SELECT 'RL003', MENU_ID FROM T_MENU WHERE MENU_CODE IN (
  'home', 'purchase', 'products', 'reports', 'approval',
  'purchase_request', 'purchase_supplier', 'product_approval',
  'reports_dashboard', 'reports_sales', 'reports_inventory', 'reports_employee',
  'approval_tasks', 'approval_instances'
);

-- 给店长角色分配门店相关菜单
INSERT INTO T_ROLE_MENU (ROLE_ID, MENU_ID)
SELECT 'RL004', MENU_ID FROM T_MENU WHERE MENU_CODE IN (
  'home', 'sales', 'inventory', 'products', 'reports', 'approval',
  'sales_order', 'sales_subsidy_photos',
  'inventory_summary', 'inventory_sn_inventory', 'inventory_batch_maintenance', 'inventory_inbound',
  'inventory_sn_trace', 'inventory_transfer', 'inventory_conversion',
  'product_product', 'product_category', 'product_price', 'product_approval',
  'reports_dashboard', 'reports_sales', 'reports_inventory', 'reports_employee',
  'approval_tasks', 'approval_instances'
);

-- 给店员角色分配基础菜单
INSERT INTO T_ROLE_MENU (ROLE_ID, MENU_ID)
SELECT 'RL005', MENU_ID FROM T_MENU WHERE MENU_CODE IN (
  'home', 'sales', 'inventory', 'reports', 'approval',
  'sales_order', 'inventory_summary', 'inventory_sn_inventory', 'inventory_inbound', 'inventory_sn_trace', 'inventory_transfer',
  'reports_dashboard', 'reports_sales', 'reports_inventory', 'reports_employee',
  'approval_tasks', 'approval_instances'
);

-- 所有账号均可进入员工业绩统计提交毛利调整申请
INSERT IGNORE INTO T_ROLE_MENU (ROLE_ID, MENU_ID)
SELECT ROLE_ID, 'M009' FROM T_ROLE WHERE STATUS = 1;

-- 所有角色都可以查看审批待办和自己的申请；流程配置仅由老板和管理员使用
INSERT IGNORE INTO T_ROLE_MENU (ROLE_ID, MENU_ID)
SELECT r.ROLE_ID, m.MENU_ID
FROM T_ROLE r JOIN T_MENU m ON m.MENU_CODE IN ('approval_tasks', 'approval_instances')
WHERE r.STATUS = 1;
INSERT IGNORE INTO T_ROLE_MENU (ROLE_ID, MENU_ID)
SELECT r.ROLE_ID, m.MENU_ID
FROM T_ROLE r JOIN T_MENU m ON m.MENU_CODE = 'approval_flows'
WHERE r.ROLE_CODE IN ('admin', 'boss') AND r.STATUS = 1;

-- 所有角色均可进入审批中心，配置权限仍由后端按 admin/BOSS 控制
INSERT IGNORE INTO T_ROLE_MENU (ROLE_ID, MENU_ID)
SELECT r.ROLE_ID, m.MENU_ID FROM T_ROLE r JOIN T_MENU m ON m.MENU_CODE = 'approval' WHERE r.STATUS = 1;

SET FOREIGN_KEY_CHECKS = 1;

-- ==========================================
-- 初始化完成
-- ==========================================
