ALTER TABLE T_ORDER_GROSS_PROFIT
  ADD COLUMN RECEIVABLE_AMOUNT DECIMAL(12,2) NOT NULL DEFAULT 0
  COMMENT '用户应收'
  AFTER RECEIVED_AMOUNT;

UPDATE T_ORDER_GROSS_PROFIT
SET RECEIVABLE_AMOUNT = RECEIVED_AMOUNT
WHERE RECEIVABLE_AMOUNT = 0
  AND RECEIVED_AMOUNT <> 0;
