ALTER TABLE T_ORDER_GROSS_PROFIT
  ADD COLUMN PRODUCT_PRICING_AMOUNT DECIMAL(12,2) NOT NULL DEFAULT 0
  COMMENT '订单产品定价合计'
  AFTER SETTLEMENT_COST_AMOUNT,
  ADD COLUMN PRODUCT_PRICING_DETAILS JSON
  COMMENT '订单产品定价明细'
  AFTER SETTLEMENT_COST_DETAILS;

UPDATE T_PRODUCT_PRICE
SET STANDARD_PRICE = COST_PRICE,
    EFFECTIVE_TIME = COALESCE(EFFECTIVE_TIME, CURRENT_TIMESTAMP)
WHERE COALESCE(STANDARD_PRICE, 0) = 0
  AND COALESCE(COST_PRICE, 0) > 0;
