-- 为采购申请明细表添加门店分配字段
ALTER TABLE T_PURCHASE_REQUEST_ITEM ADD COLUMN store_allocations TEXT NULL COMMENT '门店分配信息';

-- 为采购申请表添加时间字段
ALTER TABLE T_PURCHASE_REQUEST ADD COLUMN create_time DATETIME NULL COMMENT '创建时间';
ALTER TABLE T_PURCHASE_REQUEST ADD COLUMN update_time DATETIME NULL COMMENT '更新时间';

-- 为供应商表添加时间字段
ALTER TABLE T_SUPPLIER ADD COLUMN create_time DATETIME NULL COMMENT '创建时间';
ALTER TABLE T_SUPPLIER ADD COLUMN update_time DATETIME NULL COMMENT '更新时间';
