-- 为入库单添加采购申请关联字段和时间字段
ALTER TABLE T_INBOUND ADD COLUMN purchase_request_id VARCHAR(32) NULL COMMENT '采购申请ID';
ALTER TABLE T_INBOUND ADD COLUMN create_time DATETIME NULL COMMENT '创建时间';
ALTER TABLE T_INBOUND ADD COLUMN update_time DATETIME NULL COMMENT '更新时间';

-- 为入库明细表添加备注和门店分配字段
ALTER TABLE T_INBOUND_ITEM ADD COLUMN remark VARCHAR(512) NULL COMMENT '备注';
ALTER TABLE T_INBOUND_ITEM ADD COLUMN store_allocations TEXT NULL COMMENT '门店分配信息';
