ALTER TABLE T_DICT_PAYMENT_METHOD
  ADD COLUMN DEFAULT_TAX_RATE DECIMAL(8,4) NOT NULL DEFAULT 0
  COMMENT '默认收款手续费税率（百分数）'
  AFTER RECEIVABLE_SETTLEMENT_ACCOUNT_ID;

ALTER TABLE T_DICT_SUPPLEMENT_ITEM
  ADD COLUMN AMOUNT_TYPE VARCHAR(16) NOT NULL DEFAULT 'increase'
  COMMENT 'increase/decrease'
  AFTER AMOUNT;

CREATE TABLE IF NOT EXISTS T_ORDER_SUPPLEMENT (
  SUPPLEMENT_ID VARCHAR(32) NOT NULL,
  ORDER_ID VARCHAR(32) NOT NULL,
  ITEM_ID VARCHAR(64),
  ITEM_NAME VARCHAR(128) NOT NULL,
  AMOUNT DECIMAL(12,2) NOT NULL,
  AMOUNT_TYPE VARCHAR(16) NOT NULL DEFAULT 'increase',
  CONTENT VARCHAR(500),
  PROOF_PHOTO_URL VARCHAR(1024),
  CREATE_STAFF_ID BIGINT(20),
  CREATE_USER VARCHAR(64),
  CREATE_TIME DATETIME DEFAULT CURRENT_TIMESTAMP,
  UPDATE_TIME DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  IS_DELETED TINYINT(1) DEFAULT 0,
  PRIMARY KEY (SUPPLEMENT_ID),
  KEY idx_order_supplement (ORDER_ID, IS_DELETED)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='订单金额补录记录';

CREATE TABLE IF NOT EXISTS T_ORDER_GROSS_PROFIT (
  GROSS_PROFIT_ID VARCHAR(32) NOT NULL,
  ORDER_ID VARCHAR(32) NOT NULL,
  ORDER_NO VARCHAR(64) NOT NULL,
  STORE_ID VARCHAR(32) NOT NULL,
  FORMULA_VERSION VARCHAR(32) NOT NULL,
  RECEIVED_AMOUNT DECIMAL(12,2) NOT NULL DEFAULT 0,
  SETTLEMENT_COST_AMOUNT DECIMAL(12,2) NOT NULL DEFAULT 0,
  PAYMENT_FEE_AMOUNT DECIMAL(12,2) NOT NULL DEFAULT 0,
  INVOICE_AMOUNT DECIMAL(12,2) NOT NULL DEFAULT 0,
  VAT_TAXABLE_AMOUNT DECIMAL(12,2) NOT NULL DEFAULT 0,
  VAT_AMOUNT DECIMAL(12,2) NOT NULL DEFAULT 0,
  SUPPLEMENT_AMOUNT DECIMAL(12,2) NOT NULL DEFAULT 0,
  GROSS_PROFIT_AMOUNT DECIMAL(12,2) NOT NULL DEFAULT 0,
  PAYMENT_FEE_DETAILS JSON,
  SETTLEMENT_COST_DETAILS JSON,
  SUPPLEMENT_DETAILS JSON,
  SNAPSHOT_STATUS VARCHAR(16) NOT NULL DEFAULT 'draft',
  CALCULATED_BY VARCHAR(64),
  CALCULATED_AT DATETIME DEFAULT CURRENT_TIMESTAMP,
  CREATE_TIME DATETIME DEFAULT CURRENT_TIMESTAMP,
  UPDATE_TIME DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (GROSS_PROFIT_ID),
  UNIQUE KEY uk_order_gross_profit (ORDER_ID),
  KEY idx_gross_profit_analysis (STORE_ID, SNAPSHOT_STATUS, CALCULATED_AT)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='订单经营毛利计算快照';
