<template>
  <div class="page-container"><h2>采购进项发票管理</h2><el-alert title="待收票按有效账户付款流水计算；付款后第20天临期，第30天逾期。" type="info" :closable="false" />
    <el-row :gutter="12" class="summary"><el-col :span="8"><el-statistic title="应收票金额" :value="summary.receivable_amount||0" prefix="¥" /></el-col><el-col :span="8"><el-statistic title="未收票金额" :value="summary.unreceived_amount||0" prefix="¥" /></el-col><el-col :span="8"><el-statistic title="逾期未收" :value="summary.overdue_amount||0" prefix="¥" /></el-col></el-row>
    <el-tabs><el-tab-pane label="待收票"><el-form inline class="filters"><el-form-item label="供应商"><el-input v-model="filter.supplier" clearable /></el-form-item><el-form-item label="付款日期"><el-date-picker v-model="filter.dateRange" type="daterange" value-format="YYYY-MM-DD" /></el-form-item><el-form-item label="预警状态"><el-select v-model="filter.warning" clearable><el-option label="正常" value="normal"/><el-option label="临期" value="near_due"/><el-option label="逾期" value="overdue"/></el-select></el-form-item><el-button @click="resetFilter">重置</el-button><el-button type="primary" :disabled="!selected.length" @click="openCreate(selected)">统一登记（{{selected.length}}）</el-button></el-form>
      <el-table :data="filteredRows" border stripe @selection-change="rows=>selected=rows"><el-table-column type="selection" width="45"/><el-table-column prop="supplier_name" label="供应商"/><el-table-column prop="settlement_no" label="结算单号"/><el-table-column prop="payment_time" label="付款时间" width="170"/><el-table-column label="未收票"><template #default="{row}">¥{{row.remaining_amount}}</template></el-table-column><el-table-column label="状态"><template #default="{row}"><el-tag :type="row.warning_status==='overdue'?'danger':row.warning_status==='near_due'?'warning':'success'">{{warningText(row.warning_status)}}</el-tag></template></el-table-column><el-table-column label="操作" width="90"><template #default="{row}"><el-button link type="primary" @click="openCreate([row])">登记</el-button></template></el-table-column></el-table></el-tab-pane>
      <el-tab-pane label="已收发票"><el-table :data="invoices" border stripe><el-table-column prop="supplier_name" label="供应商"/><el-table-column prop="invoice_no" label="发票号码"/><el-table-column prop="invoice_date" label="开票日期"/><el-table-column prop="invoice_type" label="票种"/><el-table-column prop="total_amount" label="价税合计"/></el-table></el-tab-pane></el-tabs>
    <el-dialog v-model="visible" title="登记进项发票" width="760px"><el-form :model="form" label-width="100px"><el-row :gutter="12"><el-col :span="12"><el-form-item label="销方税号"><el-input v-model="form.supplierTaxNo"/></el-form-item></el-col><el-col :span="12"><el-form-item label="发票代码"><el-input v-model="form.invoiceCode"/></el-form-item></el-col><el-col :span="12"><el-form-item label="发票号码"><el-input v-model="form.invoiceNo"/></el-form-item></el-col><el-col :span="12"><el-form-item label="开票日期"><el-date-picker v-model="form.invoiceDate" value-format="YYYY-MM-DD"/></el-form-item></el-col><el-col :span="12"><el-form-item label="票种"><el-input v-model="form.invoiceType"/></el-form-item></el-col><el-col :span="12"><el-form-item label="税率"><el-input-number v-model="form.taxRate" :min="0" :max="1" :step="0.01"/></el-form-item></el-col><el-col :span="8"><el-form-item label="不含税金额"><el-input-number v-model="form.amountWithoutTax" :min="0" :precision="2"/></el-form-item></el-col><el-col :span="8"><el-form-item label="税额"><el-input-number v-model="form.taxAmount" :min="0" :precision="2"/></el-form-item></el-col><el-col :span="8"><el-form-item label="价税合计"><el-input-number v-model="form.totalAmount" :min="0" :precision="2"/></el-form-item></el-col></el-row><el-divider>本票关联付款</el-divider><el-table :data="dialogRows" border><el-table-column prop="supplier_name" label="供应商"/><el-table-column prop="settlement_no" label="结算单"/><el-table-column prop="remaining_amount" label="可分摊"/><el-table-column label="本票分摊"><template #default="{row}"><el-input-number v-model="amounts[row.payment_id]" :min="0" :max="row.remaining_amount" :precision="2"/></template></el-table-column></el-table></el-form><template #footer><el-button @click="visible=false">取消</el-button><el-button type="primary" @click="save">保存并计入已收票</el-button></template></el-dialog>
  </div>
</template>
<script setup>
import {computed,onMounted,reactive,ref} from 'vue'; import {ElMessage} from 'element-plus'; import api from '../api';
const candidates=ref([]),invoices=ref([]),summary=ref({}),visible=ref(false),selected=ref([]),dialogRows=ref([]),amounts=ref({}); const filter=reactive({supplier:'',dateRange:[],warning:''}); const blank=()=>({supplierTaxNo:'',invoiceCode:'',invoiceNo:'',invoiceDate:'',invoiceType:'增值税专用发票',taxRate:.13,amountWithoutTax:0,taxAmount:0,totalAmount:0}); const form=ref(blank());
const filteredRows=computed(()=>candidates.value.filter(r=>(!filter.supplier||String(r.supplier_name||'').includes(filter.supplier))&&(!filter.warning||r.warning_status===filter.warning)&&(!filter.dateRange.length||(String(r.payment_time).slice(0,10)>=filter.dateRange[0]&&String(r.payment_time).slice(0,10)<=filter.dateRange[1])))); const warningText=s=>({normal:'正常',near_due:'临期',overdue:'逾期'}[s]||'正常');
const load=async()=>{const [a,b]=await Promise.all([api.getPurchaseInvoiceCandidates({status:'open'}),api.getPurchaseInvoices()]);candidates.value=a.data?.list||[];summary.value=a.data?.summary||{};invoices.value=b.data?.list||[]}; const resetFilter=()=>Object.assign(filter,{supplier:'',dateRange:[],warning:''}); const openCreate=rows=>{form.value=blank();dialogRows.value=rows;amounts.value=Object.fromEntries(rows.map(r=>[r.payment_id,r.remaining_amount]));visible.value=true}; const save=async()=>{try{await api.createPurchaseInvoice({...form.value,allocations:dialogRows.value.map(r=>({paymentId:r.payment_id,settlementId:r.settlement_id,amount:amounts.value[r.payment_id]||0}))});ElMessage.success('已登记');visible.value=false;selected.value=[];load()}catch(e){ElMessage.error(e.response?.data?.message||e.message)}}; onMounted(load);
</script>
<style scoped>.summary{margin:16px 0}.filters{margin:16px 0 4px}</style>
